project_id = "jzkjykmrwisijiqlwuua"

[functions.insert-pari-results]
verify_jwt = false

[functions.ai-consolidation-analysis]
verify_jwt = false

[functions.populate-vector-store]
verify_jwt = false

[functions.chat-intelligence]
verify_jwt = false
