project_id = "jzkjykmrwisijiqlwuua"

[functions.insert-rix-results]
verify_jwt = false

[functions.ai-consolidation-analysis]
verify_jwt = false

[functions.populate-vector-store]
verify_jwt = false

[functions.populate-feedback-vectors]
verify_jwt = false

[functions.chat-intelligence]
verify_jwt = false

[functions.generate-news-story]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.analyze-user-profiles]
verify_jwt = false

[functions.generate-marketing-notifications]
verify_jwt = false

[functions.sanitize-rix-insert]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.rss-feed]
verify_jwt = false

[functions.rix-search-v2]
verify_jwt = false

[functions.rix-analyze-v2]
verify_jwt = false
