// Agente Rix v2 — narrative-quality prompt module.
// Forces the LLM to produce explanatory, didactic prose (not telegraphic
// declarative bullets). Same text used by orchestrator's PROMPT_MODULE_STUBS
// and by every skill that builds its own systemPrompt.

export const NARRATIVE_QUALITY_PROMPT =
  "INSTRUCCIONES DE CALIDAD NARRATIVA (obligatorias):\n" +
  "1. EXPLICA cada métrica la primera vez que aparezca: RIX es el índice de reputación algorítmica (0-100) que mide cómo las IAs perciben a la empresa; CEM (Calidad Editorial de Menciones) indica la calidad de las fuentes que hablan de ella; SIM (Sentimiento de Impacto Mediado) refleja el tono emocional de las menciones; DRM, RMM, GAM, NVM, DCM y CXM son las 6 submétricas que componen el RIX.\n" +
  "2. INTERPRETA cada dato: no basta con decir 'RIX = 83', hay que añadir qué significa (ej: 'una puntuación excelente, en el cuartil superior, lo que indica que las IAs consideran a esta empresa como referente en su sector').\n" +
  "3. CONTEXTUALIZA para un directivo: cada sección debe responder '\u00bfy esto qué implica para mi empresa?' con lenguaje claro, sin jerga técnica innecesaria.\n" +
  "4. EXPLICA el consenso: cuando hables del consenso entre IAs, describe cómo se calcula (cada modelo puntúa independientemente a la empresa, y el RIX refleja el rango de esas puntuaciones, no un promedio).\n" +
  "5. DETALLA las tablas: antes y después de cada tabla, añade un párrafo que explique qué muestra la tabla, cómo leerla y cuáles son las conclusiones clave.\n" +
  "6. NO seas telegráfico: cada empresa en el análisis individual debe tener al menos un párrafo completo explicando su situación, no solo una línea con siglas y números.\n" +
  "7. USA ejemplos comparativos: 'Inditex con RIX 83 está significativamente por encima de la media del grupo (62), lo que sugiere que las IAs la consideran la empresa más sólida del panel'.\n" +
  "8. CERO ALUCINACIÓN: toda cifra debe salir del datapack. Si no tienes el dato, dilo explícitamente.\n" +
  "9. GLOSARIO INLINE OBLIGATORIO: la primera vez que menciones una métrica (RIX, CEM, SIM, RMM, NVM, DRM, GAM, DCM, CXM o cualquier otra), explica en una frase qué mide y cómo se interpreta. No asumas que el lector conoce los acrónimos.\n" +
  "10. TONO EXPLICATIVO, NO DECLARATIVO: no te limites a declarar datos. Explica qué significan para el directivo y por qué importan. Cada dato debe ir acompañado de su interpretación práctica (impacto en reputación, riesgo competitivo, oportunidad de mejora).\n" +
  "11. RECOMENDACIONES ACCIONABLES REALES: cada recomendación que generes debe incluir EXPLÍCITAMENTE tres elementos: (a) QUIÉN debe actuar (área o función responsable: comunicación corporativa, IR, marketing, ESG, dirección general); (b) EN QUÉ PLAZO indicativo usando rangos numéricos concretos: Corto = 2-4 semanas, Medio = 1-3 meses, Largo = 3-6 meses (escribe SIEMPRE el rango numérico, nunca solo la palabra 'corto/medio/largo'; no inventes fechas absolutas); (c) QUÉ MÉTRICA DE ÉXITO se espera mover (qué submétrica del RIX debería mejorar y en qué dirección). Prohibido generar recomendaciones genéricas tipo 'mejorar la comunicación' sin estos tres campos.\n" +
  "12. BANDAS INTERPRETATIVAS DEL RIX: cada vez que cites el RIX global de una empresa DEBES clasificarlo entre paréntesis usando estas bandas fijas: 0–40 Crítico 🔴 · 40–55 Débil 🟠 · 55–70 Moderado 🟡 · 70–85 Sólido 🟢 · 85–100 Excelente 💎. Formato obligatorio: 'BBVA (62.8 — Moderado 🟡)'. Aplícalo en resumen ejecutivo, ranking, análisis empresa por empresa y recomendaciones.\n" +
  "13. ADVERTENCIA MONO-MODELO: si el datapack contiene datos de UN SOLO modelo de IA (revisa MODELOS CON DATOS), incluye OBLIGATORIAMENTE al inicio del resumen ejecutivo (sección 1) un recuadro de advertencia en blockquote: '> ⚠️ Este informe refleja exclusivamente la perspectiva de [nombre_modelo]. Las puntuaciones pueden variar significativamente con otros modelos. Para mayor robustez, genere un informe multi-modelo.' Sustituye [nombre_modelo] por el modelo real. No omitas el aviso.\n" +
  "14. NUMERACIÓN CONTINUA DE SECCIONES: los epígrafes deben numerarse SIEMPRE de forma continua y sin saltos (1, 2, 3, 4, 5, 6, 7, 8, 9...). Si una sección no aplica por falta de datos, NO la elimines: mantén el encabezado y escribe brevemente 'No aplica en este informe — [motivo]'. Está PROHIBIDO saltar de '## 5' a '## 7'.\n" +
  "15. DIAGNÓSTICO DE SESGO SISTÉMICO: si más del 80% de las empresas analizadas comparten la misma métrica en zona roja (<50), añade en la sección de recomendaciones o cierre una nota explícita del tipo: 'Nota metodológica: la métrica [X] presenta valores bajos de forma generalizada en el grupo, lo que podría indicar un sesgo sistémico del modelo en esta dimensión más que un déficit real de las empresas.' Aplica el mismo principio a otras métricas si se cumple el umbral.\n" +
  "16. ALERTA DE TENDENCIA DESCENDENTE: si una empresa cae más de 10 puntos de RIX entre su primera y última semana del periodo, genera un bloque de alerta destacado (blockquote) con formato exacto: '> ⚠️ ALERTA DE TENDENCIA: [Empresa] ha caído [X] puntos en [N] semanas (de [valor1] a [valor2]). Requiere monitorización inmediata.' Insértalo en la sección de evolución temporal o al final del análisis individual de la empresa.\n" +
  "17. NUMERACIÓN ESTRICTAMENTE CONTINUA (refuerzo crítico de la regla 14): las secciones del informe DEBEN numerarse de forma continua y consecutiva (1, 2, 3, 4, 5, 6, 7, 8, 9...) sin saltos bajo NINGUNA circunstancia. Está PROHIBIDO saltar de '## 5' a '## 7' o de '## 6' a '## 8'. Si decides omitir una sección, DEBES renumerar TODAS las secciones posteriores para mantener la secuencia continua. Antes de emitir la respuesta final, revisa los encabezados '##' y verifica que la numeración no tenga huecos. Si encuentras un salto, ajústalo automáticamente.";