-- Fix existing {TICKER} placeholders in pari_runs table by mapping target_name to correct ticker
UPDATE pari_runs 
SET "05_ticker" = CASE 
    WHEN LOWER("03_target_name") LIKE '%acciona energía%' OR LOWER("03_target_name") LIKE '%acciona energia%' THEN 'ANE.MC'
    WHEN LOWER("03_target_name") LIKE '%acciona%' THEN 'ANA.MC'
    WHEN LOWER("03_target_name") LIKE '%acerinox%' THEN 'ACX.MC'
    WHEN LOWER("03_target_name") LIKE '%acs%' THEN 'ACS.MC'
    WHEN LOWER("03_target_name") LIKE '%aena%' THEN 'AENA.MC'
    WHEN LOWER("03_target_name") LIKE '%amadeus%' THEN 'AMS.MC'
    WHEN LOWER("03_target_name") LIKE '%arcelormittal%' THEN 'MTS.MC'
    WHEN LOWER("03_target_name") LIKE '%banco sabadell%' OR LOWER("03_target_name") LIKE '%sabadell%' THEN 'SAB.MC'
    WHEN LOWER("03_target_name") LIKE '%banco santander%' OR LOWER("03_target_name") LIKE '%santander%' THEN 'SAN.MC'
    WHEN LOWER("03_target_name") LIKE '%bankinter%' THEN 'BKT.MC'
    WHEN LOWER("03_target_name") LIKE '%bbva%' THEN 'BBVA.MC'
    WHEN LOWER("03_target_name") LIKE '%caixabank%' THEN 'CABK.MC'
    WHEN LOWER("03_target_name") LIKE '%cellnex%' THEN 'CLNX.MC'
    WHEN LOWER("03_target_name") LIKE '%colonial%' THEN 'COL.MC'
    WHEN LOWER("03_target_name") LIKE '%enagás%' OR LOWER("03_target_name") LIKE '%enagas%' THEN 'ENG.MC'
    WHEN LOWER("03_target_name") LIKE '%endesa%' THEN 'ELE.MC'
    WHEN LOWER("03_target_name") LIKE '%ferrovial%' THEN 'FER.MC'
    WHEN LOWER("03_target_name") LIKE '%fluidra%' THEN 'FDR.MC'
    WHEN LOWER("03_target_name") LIKE '%grifols%' THEN 'GRF.MC'
    WHEN LOWER("03_target_name") LIKE '%iag%' OR LOWER("03_target_name") LIKE '%international airlines%' THEN 'IAG.MC'
    WHEN LOWER("03_target_name") LIKE '%iberdrola%' THEN 'IBE.MC'
    WHEN LOWER("03_target_name") LIKE '%inditex%' THEN 'ITX.MC'
    WHEN LOWER("03_target_name") LIKE '%indra%' THEN 'IDR.MC'
    WHEN LOWER("03_target_name") LIKE '%logista%' THEN 'LOG.MC'
    WHEN LOWER("03_target_name") LIKE '%mapfre%' THEN 'MAP.MC'
    WHEN LOWER("03_target_name") LIKE '%merlin properties%' OR LOWER("03_target_name") LIKE '%merlin%' THEN 'MRL.MC'
    WHEN LOWER("03_target_name") LIKE '%naturgy%' THEN 'NTGY.MC'
    WHEN LOWER("03_target_name") LIKE '%puig%' THEN 'PUIG.MC'
    WHEN LOWER("03_target_name") LIKE '%redeia%' OR LOWER("03_target_name") LIKE '%ree%' THEN 'RED.MC'
    WHEN LOWER("03_target_name") LIKE '%repsol%' THEN 'REP.MC'
    WHEN LOWER("03_target_name") LIKE '%laboratorios rovi%' OR LOWER("03_target_name") LIKE '%rovi%' THEN 'ROVI.MC'
    WHEN LOWER("03_target_name") LIKE '%sacyr%' THEN 'SCYR.MC'
    WHEN LOWER("03_target_name") LIKE '%solaria%' THEN 'SLR.MC'
    WHEN LOWER("03_target_name") LIKE '%telefónica%' OR LOWER("03_target_name") LIKE '%telefonica%' THEN 'TEF.MC'
    WHEN LOWER("03_target_name") LIKE '%unicaja%' THEN 'UNI.MC'
    ELSE "05_ticker"  -- Keep existing ticker if no match found
END
WHERE "05_ticker" = '{TICKER}' OR "05_ticker" IS NULL;