-- Insert second example row in pari_runs table with PERPLEXITY model data
INSERT INTO pari_runs (
  run_id,
  model_name,
  target_name,
  target_type,
  ticker,
  period_from,
  period_to,
  tz,
  pari_score,
  lns_score,
  lns_peso,
  lns_categoria,
  es_score,
  es_peso,
  es_categoria,
  sam_score,
  sam_peso,
  sam_categoria,
  rm_score,
  rm_peso,
  rm_categoria,
  clr_score,
  clr_peso,
  clr_categoria,
  gip_score,
  gip_peso,
  gip_categoria,
  kgi_score,
  kgi_peso,
  kgi_categoria,
  mpi_score,
  mpi_peso,
  mpi_categoria,
  resumen,
  puntos_clave,
  palabras,
  num_fechas,
  num_citas,
  temporal_alignment,
  citation_density,
  flags,
  weights,
  subscores
) VALUES (
  'REPSOL-PERPLEXITY-20240915',
  'PERPLEXITY',
  'Repsol',
  'Repsol',
  'REP',
  '2024-09-09',
  '2024-09-15',
  'Europe/Madrid',
  32,
  7,
  25,
  'Insuficiente',
  52,
  15,
  'Mejorable',
  25,
  12,
  'Insuficiente',
  27,
  8,
  'Insuficiente',
  32,
  12,
  'Insuficiente',
  35,
  12,
  'Insuficiente',
  60,
  6,
  'Mejorable',
  55,
  10,
  'Mejorable',
  'Durante la semana 11–18 septiembre 2025, la reapertura del caso del derrame en Perú —con un recurso de nulidad de las fiscalías contra un acuerdo que benefició a Repsol— reaviva riesgos legales y reputacionales significativos, en un contexto de litigios por greenwashing y presión financiera. El texto aporta contexto abundante y fuentes, aunque mezcla información reciente y antigua y muestra algunas discrepancias en fuentes sobre resultados judiciales.',
  '["Fiscalías ambientales de Perú presentaron recurso de nulidad (6 sep 2025) contra un acuerdo que reducía responsabilidades de Repsol por el derrame de 15 ene 2022.", "Se documentan posibles irregularidades procesales en la aprobación del acuerdo original y cambio de fiscal responsable, aumentando el escrutinio público.", "Contexto amplio de litigios por greenwashing (demanda de Iberdrola, denuncias de ONG) y presiones regulatorias en España/EU.", "Impacto reputacional reforzado por la magnitud del derrame, consecuencias sociales/ambientales persistentes y cuestionamientos sobre la remediación."]'::jsonb,
  1740,
  12,
  15,
  0.3,
  0.009,
  '["datos_antiguos", "dudas_no_aclaradas", "cutoff_disclaimer"]'::jsonb,
  '{
    "LNS": 25,
    "ES": 15,
    "SAM": 12,
    "RM": 8,
    "CLR": 12,
    "GIP": 12,
    "KGI": 6,
    "MPI": 10
  }'::jsonb,
  '[
    {
      "label": "Calidad de la narrativa",
      "label_en_sigla": "LLM Narrative Score — LNS",
      "score": 7,
      "peso": 25,
      "categoria": "Insuficiente"
    },
    {
      "label": "Fortaleza de evidencia",
      "label_en_sigla": "Evidence Strength — ES",
      "score": 52,
      "peso": 15,
      "categoria": "Mejorable"
    },
    {
      "label": "Mezcla de autoridad de fuentes",
      "label_en_sigla": "Source Authority Mix — SAM",
      "score": 25,
      "peso": 12,
      "categoria": "Insuficiente"
    },
    {
      "label": "Actualidad y empuje",
      "label_en_sigla": "Recency & Momentum — RM",
      "score": 27,
      "peso": 8,
      "categoria": "Insuficiente"
    },
    {
      "label": "Controversia y riesgo legal (reverso)",
      "label_en_sigla": "Controversy & Legal Risk — CLR",
      "score": 32,
      "peso": 12,
      "categoria": "Insuficiente"
    },
    {
      "label": "Percepción de independencia de gobierno",
      "label_en_sigla": "Governance Independence Perception — GIP",
      "score": 35,
      "peso": 12,
      "categoria": "Insuficiente"
    },
    {
      "label": "Integridad del grafo de conocimiento",
      "label_en_sigla": "Knowledge Graph Integrity — KGI",
      "score": 60,
      "peso": 6,
      "categoria": "Mejorable"
    },
    {
      "label": "Impacto de mercado/ejecución",
      "label_en_sigla": "Market/Performance Impact — MPI",
      "score": 55,
      "peso": 10,
      "categoria": "Mejorable"
    }
  ]'::jsonb
);