-- Insert example row in pari_runs table with the provided JSON data
INSERT INTO pari_runs (
  run_id,
  model_name,
  target_name,
  target_type,
  ticker,
  period_from,
  period_to,
  tz,
  pari_score,
  lns_score,
  lns_peso,
  lns_categoria,
  es_score,
  es_peso,
  es_categoria,
  sam_score,
  sam_peso,
  sam_categoria,
  rm_score,
  rm_peso,
  rm_categoria,
  clr_score,
  clr_peso,
  clr_categoria,
  gip_score,
  gip_peso,
  gip_categoria,
  kgi_score,
  kgi_peso,
  kgi_categoria,
  mpi_score,
  mpi_peso,
  mpi_categoria,
  resumen,
  puntos_clave,
  palabras,
  num_fechas,
  num_citas,
  temporal_alignment,
  citation_density,
  flags,
  weights,
  subscores
) VALUES (
  'REPSOL-CHATGPT-20240915',
  'ChatGPT',
  'Repsol',
  'Repsol',
  'REP',
  '2024-09-09',
  '2024-09-15',
  'Europe/Madrid',
  57,
  56,
  25,
  'Mejorable',
  74,
  15,
  'Bueno',
  26,
  12,
  'Insuficiente',
  10,
  8,
  'Insuficiente',
  81,
  12,
  'Bueno',
  60,
  12,
  'Mejorable',
  80,
  6,
  'Bueno',
  65,
  10,
  'Mejorable',
  'La semana recoge menciones variadas sobre Repsol: una gran emisión de bonos, una mejora de recomendación por JPMorgan, resultados semestrales débiles, y actividades de marca y patrocinio; también aparece un requerimiento del Ministerio de Consumo por presunto contenido publicitario engañoso. Las fuentes citadas son mayoritariamente medios y comunicados empresariales, con escasa cobertura estrictamente dentro de la ventana indicada.',
  '["Emisión de bonos por 2.500 MUSD con alta demanda (cita a Cinco Días).", "JPMorgan elevó recomendación y precio objetivo (mencionado vía Cinco Días).", "Resultados H1 2025: beneficio neto 603M€ (-62,9%), impacto de 175M€ por apagón.", "Requerimiento del Ministerio de Consumo por denuncia de ecologistas sobre biocombustibles.", "Actividades de marca y eventos (patrocinio Cartagena Suena; Technology Trends Summit).", "Fuentes presentes pero con poca concentración de noticias dentro de la semana evaluada."]'::jsonb,
  300,
  10,
  8,
  0,
  0.03,
  '["datos_antiguos", "dudas_no_aclaradas"]'::jsonb,
  '{
    "LNS": 25,
    "ES": 15,
    "SAM": 12,
    "RM": 8,
    "CLR": 12,
    "GIP": 12,
    "KGI": 6,
    "MPI": 10
  }'::jsonb,
  '[
    {
      "label": "Calidad de la narrativa",
      "label_en_sigla": "LLM Narrative Score — LNS",
      "score": 56,
      "peso": 25,
      "categoria": "Mejorable"
    },
    {
      "label": "Fortaleza de evidencia",
      "label_en_sigla": "Evidence Strength — ES",
      "score": 74,
      "peso": 15,
      "categoria": "Bueno"
    },
    {
      "label": "Mezcla de autoridad de fuentes",
      "label_en_sigla": "Source Authority Mix — SAM",
      "score": 26,
      "peso": 12,
      "categoria": "Insuficiente"
    },
    {
      "label": "Actualidad y empuje",
      "label_en_sigla": "Recency & Momentum — RM",
      "score": 10,
      "peso": 8,
      "categoria": "Insuficiente"
    },
    {
      "label": "Controversia y riesgo legal (reverso)",
      "label_en_sigla": "Controversy & Legal Risk — CLR",
      "score": 81,
      "peso": 12,
      "categoria": "Bueno"
    },
    {
      "label": "Percepción de independencia de gobierno",
      "label_en_sigla": "Governance Independence Perception — GIP",
      "score": 60,
      "peso": 12,
      "categoria": "Mejorable"
    },
    {
      "label": "Integridad del grafo de conocimiento",
      "label_en_sigla": "Knowledge Graph Integrity — KGI",
      "score": 80,
      "peso": 6,
      "categoria": "Bueno"
    },
    {
      "label": "Impacto de mercado/ejecución",
      "label_en_sigla": "Market/Performance Impact — MPI",
      "score": 65,
      "peso": 10,
      "categoria": "Mejorable"
    }
  ]'::jsonb
);