
-- Create platform_snapshots table
CREATE TABLE public.platform_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  detailed_description text NOT NULL,
  changes jsonb NOT NULL DEFAULT '[]'::jsonb,
  snapshot_type text NOT NULL DEFAULT 'feature',
  tags text[] DEFAULT '{}'::text[],
  metrics_at_snapshot jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE public.platform_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Snapshots are publicly readable"
  ON public.platform_snapshots FOR SELECT
  USING (true);

CREATE POLICY "Service role can manage snapshots"
  ON public.platform_snapshots FOR ALL
  USING (true)
  WITH CHECK (true);

-- Seed historical snapshots
INSERT INTO public.platform_snapshots (version, title, summary, detailed_description, changes, snapshot_type, tags, metrics_at_snapshot, snapshot_date) VALUES

('1.0.0', 'Creación del Índice RIX', 
'Diseño e implementación del Reputation Intelligence Index (RIX), un índice propietario de 50 métricas ponderadas que mide la reputación corporativa a través de inteligencia artificial.',
E'## Arquitectura del Índice RIX\n\n### Decisión fundamental\nSe diseñó un sistema de evaluación con **50 métricas** organizadas en **8 macro-categorías (metacriterios)** que cubren todas las dimensiones de la reputación corporativa:\n\n| Metacriterio | Código | Peso | Métricas |\n|---|---|---|---|\n| Narrative & Visibility | NVM | 15% | 7 métricas |\n| Digital Resonance | DRM | 12% | 6 métricas |\n| Stakeholder Impact | SIM | 14% | 7 métricas |\n| Risk & Media Management | RMM | 13% | 6 métricas |\n| Corporate Ethics | CEM | 12% | 6 métricas |\n| Growth & Adaptability | GAM | 11% | 6 métricas |\n| Data Consistency | DCM | 11% | 6 métricas |\n| Customer Experience | CXM | 12% | 6 métricas |\n\n### Metodología de puntuación\n- Cada métrica se puntúa de 0 a 100\n- Pesos internos dentro de cada metacriterio\n- Score final RIX = suma ponderada de los 8 metacriterios\n- Escala resultante: 0-100 puntos\n\n### Tablas creadas\n- `evaluation`: Evaluaciones legacy con 2 modelos\n- `by_metric`: Desglose por métrica individual\n- `contadores`: Contadores de palabras, citas, fechas\n- `meta_weight_scheme`: Esquema de pesos por evaluación\n- `executive_notes`: Notas ejecutivas\n- `recommendations_tactical`: Recomendaciones tácticas\n\n### Decisiones de arquitectura\n- Se eligió Supabase como backend por su capacidad de RLS, Edge Functions y tiempo real\n- Estructura relacional normalizada para análisis cruzados\n- Sistema de flags para detectar anomalías en las respuestas de los modelos',
'["Diseño de 50 métricas de reputación organizadas en 8 metacriterios","Sistema de pesos ponderados con esquema configurable por evaluación","Estructura de base de datos relacional con 6 tablas interconectadas","Sistema de flags para detección de anomalías en respuestas IA","Notas ejecutivas y recomendaciones tácticas por evaluación"]'::jsonb,
'milestone', ARRAY['RIX','metodología','fundacional'], '{"metricas": 50, "metacriterios": 8, "modelos": 0}'::jsonb, '2024-10-15'),

('1.1.0', 'Primer barrido: ChatGPT + Perplexity',
'Implementación del primer sistema de evaluación dual con ChatGPT y Perplexity como modelos de IA para generar análisis de reputación.',
E'## Primer sistema de evaluación dual\n\n### Arquitectura del barrido\nSe implementó un sistema donde cada empresa es analizada por **dos modelos de IA** de forma independiente:\n\n1. **ChatGPT (OpenAI)**: Modelo generalista con amplio conocimiento\n2. **Perplexity**: Modelo con acceso a búsqueda en tiempo real\n\n### Flujo de evaluación\n```\nEmpresa → Prompt estandarizado → ChatGPT → Parsing → 50 métricas\n                                → Perplexity → Parsing → 50 métricas\n                                → Comparación → Score compuesto\n```\n\n### Tabla `evaluation`\n- `composite_chatgpt`: Score compuesto ChatGPT\n- `composite_perplexity`: Score compuesto Perplexity\n- `composite_winner`: Modelo ganador\n- `composite_delta_abs`: Diferencia absoluta\n- `metrics_won_chatgpt/perplexity/ties`: Métricas ganadas por cada modelo\n\n### Resultados iniciales\n- ~30 empresas del IBEX 35 evaluadas\n- Diferencias promedio entre modelos: 8-15 puntos\n- Perplexity tendía a scores más altos por acceso a datos recientes\n- ChatGPT más conservador pero más consistente',
'["Integración con API de OpenAI (ChatGPT-4)","Integración con API de Perplexity","Sistema de parsing de respuestas brutas a 50 métricas numéricas","Comparación automática entre modelos con delta y ganador","Primeras ~30 empresas IBEX evaluadas"]'::jsonb,
'feature', ARRAY['ChatGPT','Perplexity','barrido','V1'], '{"empresas_evaluadas": 30, "modelos": 2}'::jsonb, '2024-11-01'),

('1.2.0', 'Chat Inteligente con Vector Store',
'Implementación del agente conversacional con memoria vectorial para consultas sobre datos de reputación corporativa.',
E'## Sistema de Chat Inteligente\n\n### Arquitectura RAG (Retrieval-Augmented Generation)\nSe implementó un sistema completo de RAG usando embeddings para enriquecer las respuestas del chat:\n\n1. **Vector Store** (`documents` table): Almacena chunks de datos con embeddings OpenAI\n2. **Búsqueda semántica**: `match_documents` RPC para encontrar contexto relevante\n3. **Chat Intelligence** (Edge Function): Orquesta la conversación con contexto\n\n### Edge Function `chat-intelligence`\n- Recibe pregunta del usuario\n- Busca en Vector Store documentos relevantes\n- Consulta datos estructurados de `rix_runs`\n- Construye prompt con contexto completo\n- Streaming SSE para respuesta en tiempo real\n- Guarda historial en `chat_intelligence_sessions`\n\n### Tabla `chat_vector_memory`\n- `embedding`: Vector de 1536 dimensiones (OpenAI)\n- `mensaje_usuario`: Pregunta original\n- `respuesta_bot`: Respuesta generada\n- `metadata`: Contexto adicional (empresa, semana, etc.)\n\n### Funcionalidades\n- Respuestas contextualizadas con datos reales\n- Sugerencias de preguntas inteligentes\n- Historial de conversación persistente\n- Soporte multiidioma (ES/EN)',
'["Vector Store con embeddings OpenAI (1536 dimensiones)","Edge Function chat-intelligence con streaming SSE","Búsqueda semántica con match_documents RPC","Historial de conversaciones persistente","Sugerencias de preguntas contextuales","Soporte multiidioma español/inglés"]'::jsonb,
'feature', ARRAY['chat','vector-store','RAG','OpenAI'], '{"documentos_vectorizados": 500}'::jsonb, '2024-11-20'),

('2.0.0', 'Agente Rix Flotante',
'Chat disponible en todas las páginas con contexto dinámico según la página actual del usuario.',
E'## Chat Flotante Universal\n\n### Componente `FloatingChat`\nSe creó un componente de chat que se renderiza en todas las páginas de la aplicación:\n\n- **Posición**: Flotante en esquina inferior derecha\n- **Contexto dinámico**: El hook `usePageContext` detecta la página actual y adapta el system prompt\n- **Persistencia**: Las conversaciones se guardan en `user_conversations` y `chat_intelligence_sessions`\n- **Sugerencias**: Se generan sugerencias contextuales basadas en la página actual\n\n### Páginas con contexto especializado\n- **Dashboard**: Contexto de la empresa actual del usuario\n- **Market Evolution**: Contexto de tendencias de mercado\n- **RIX Run Detail**: Contexto del análisis específico que está viendo\n- **Landing**: Contexto comercial para visitantes\n\n### Arquitectura\n```\nFloatingChat → ChatContext → usePageContext → Edge Function\n                           → useSmartSuggestions\n                           → ChatMessages + ChatInput\n```',
'["Chat disponible en todas las páginas de la aplicación","Contexto dinámico según página actual (usePageContext)","Persistencia de conversaciones con user_conversations","Sugerencias contextuales por página","Minimizable y redimensionable"]'::jsonb,
'feature', ARRAY['chat','UX','flotante'], '{}'::jsonb, '2024-11-20'),

('2.1.0', 'Vector Store Mejorado',
'Indexación de respuestas completas de los modelos de IA con sincronización incremental automática.',
E'## Mejora del Vector Store\n\n### Problema\nEl Vector Store inicial solo contenía datos estructurados (scores numéricos). Las respuestas brutas de los modelos (`res_gpt_bruto`, `res_perplex_bruto`) no estaban indexadas, perdiendo contexto valioso.\n\n### Solución\nSe amplió la Edge Function `populate-vector-store` para:\n\n1. **Indexar respuestas brutas**: Cada respuesta completa de cada modelo se chunka y vectoriza\n2. **Sincronización incremental**: Solo procesa registros nuevos desde la última sincronización\n3. **Metadatos enriquecidos**: Cada chunk incluye empresa, modelo, semana, metacriterio\n\n### Impacto\n- Calidad de respuestas del chat mejoró significativamente\n- El agente ahora puede citar análisis específicos de cada modelo\n- Búsquedas semánticas más precisas por tener más contexto',
'["Indexación de respuestas brutas de todos los modelos IA","Sincronización incremental automática","Metadatos enriquecidos por chunk (empresa, modelo, semana)","Mejora significativa en calidad de respuestas del chat"]'::jsonb,
'improvement', ARRAY['vector-store','calidad','indexación'], '{"documentos_vectorizados": 2000}'::jsonb, '2024-11-28'),

('2.2.0', 'Generador de Boletines Ejecutivos',
'Sistema de generación automática de boletines ejecutivos personalizados por empresa con análisis competitivo.',
E'## Boletines Ejecutivos\n\n### Funcionalidad\nSe implementó un generador de informes ejecutivos que:\n\n1. **Selección de empresa**: El usuario elige una empresa del universo RIX\n2. **Recopilación de datos**: Se obtienen los últimos análisis RIX de la empresa y sus competidores\n3. **Generación IA**: Un prompt especializado genera un boletín con:\n   - Resumen ejecutivo\n   - Evolución del score RIX\n   - Análisis por metacriterio\n   - Comparativa competitiva\n   - Recomendaciones tácticas\n4. **Formato magazine**: Diseño profesional para impresión/PDF\n\n### Componente `CompanyBulletinViewer`\n- Renderizado HTML rico con estilos de impresión\n- Gráficos de evolución temporal\n- Tablas comparativas con competidores\n- Exportable a PDF',
'["Boletines ejecutivos personalizados por empresa","Análisis competitivo automático con competidores verificados","Formato magazine profesional para impresión","Gráficos de evolución temporal integrados"]'::jsonb,
'feature', ARRAY['boletines','reportes','ejecutivo'], '{}'::jsonb, '2024-12-01'),

('2.3.0', 'Enriquecimiento por Rol Profesional',
'Sistema de 15 roles profesionales que adaptan las respuestas del chat según el perfil del usuario.',
E'## Roles Profesionales\n\n### Motivación\nDiferentes usuarios necesitan diferentes perspectivas sobre los mismos datos. Un CEO necesita visión estratégica, un analista necesita datos granulares, un periodista necesita narrativa.\n\n### Implementación\nSe crearon **15 roles profesionales** en `src/lib/chatRoles.ts`:\n\n| Rol | Perspectiva |\n|---|---|\n| CEO / Director General | Estratégica y visión global |\n| Director de Comunicación | Reputación y medios |\n| Analista Financiero | Datos y métricas cuantitativas |\n| Inversor | Riesgo y oportunidad |\n| Periodista | Narrativa y fuentes |\n| Consultor Estratégico | Frameworks y metodologías |\n| Director de RRHH | Employer branding |\n| Director Comercial | Oportunidades de negocio |\n| Regulador | Cumplimiento normativo |\n| Académico | Rigor metodológico |\n| Community Manager | Social media y engagement |\n| Director de ESG | Sostenibilidad |\n| Abogado Corporativo | Riesgos legales |\n| Director de Innovación | Tendencias tecnológicas |\n| Competidor | Benchmarking |\n\n### Tabla `role_enrichment_analytics`\n- Tracking de qué roles se usan más\n- Analytics en panel de admin\n- Respuestas expandidas de 2500-5000 palabras según rol',
'["15 roles profesionales con perspectivas especializadas","Respuestas expandidas de 2500-5000 palabras según rol","Analytics de uso de roles en admin","Adaptación automática del system prompt por rol","Tabla role_enrichment_analytics para tracking"]'::jsonb,
'feature', ARRAY['roles','personalización','chat'], '{"roles_disponibles": 15}'::jsonb, '2024-12-05'),

('2.4.0', 'Análisis de Perfiles de Usuario con IA',
'Segmentación automática de usuarios en personas/estereotipos basada en su comportamiento real de uso.',
E'## Perfiles de Usuario con IA\n\n### Sistema de Personas\nSe implementó un análisis automático de comportamiento de usuarios que:\n\n1. **Recopila métricas**: Conversaciones, enriquecimientos, documentos generados, frecuencia de uso\n2. **Análisis IA**: Edge Function `analyze-user-profiles` usa OpenAI para segmentar usuarios\n3. **Genera personas**: Arquetipos como "Explorador Activo", "Analista Profundo", "Observador Casual"\n\n### Datos analizados por usuario\n- Total de conversaciones\n- Roles profesionales más usados\n- Empresas mencionadas frecuentemente\n- Documentos generados\n- Frecuencia de sesiones\n- Profundidad de interacción\n\n### Visualización en Admin\n- Distribución de personas con gráfico de barras\n- Detalle por persona: usuarios, métricas promedio\n- Tabla de actividad individual con métricas\n- Refresh manual con botón en admin',
'["Segmentación automática de usuarios en personas","Edge Function analyze-user-profiles con OpenAI","Métricas de comportamiento por usuario","Visualización en panel admin con distribución","Arquetipos generados dinámicamente por IA"]'::jsonb,
'feature', ARRAY['perfiles','IA','segmentación','admin'], '{}'::jsonb, '2024-12-07'),

('2.5.0', 'Marketing Inbound con IA',
'Sistema de generación de notificaciones personalizadas y plan de inbound automatizado usando IA.',
E'## Marketing Inbound Automatizado\n\n### Arquitectura\n\n1. **Generación de notificaciones**: Edge Function `generate-marketing-notifications`\n   - Recibe personas/segmentos objetivo\n   - Genera contenido personalizado por perfil\n   - Crea notificaciones push adaptadas\n\n2. **Plan de inbound**: Generación de calendario semanal\n   - Contenido adaptado a cada persona\n   - Frecuencia óptima por perfil\n   - Templates reutilizables\n\n### Tablas involucradas\n- `marketing_campaigns`: Campañas con templates\n- `user_notifications`: Notificaciones individuales\n- `notification_analytics`: Tracking de apertura/click\n\n### Panel de Admin\n- Selector de personas objetivo\n- Preview de notificaciones antes de enviar\n- Dashboard de métricas (enviadas, leídas, clicks)\n- Generación de plan inbound completo',
'["Generación de notificaciones personalizadas por perfil de usuario usando IA","Plan de inbound completo generado dinámicamente","Calendario semanal de push notifications adaptado a cada persona","Guardado del último plan generado para seguimiento","Dashboard de métricas de marketing en admin"]'::jsonb,
'feature', ARRAY['marketing','inbound','notificaciones','IA'], '{}'::jsonb, '2024-12-08'),

('3.0.0', 'Pipeline V2: Expansión a 6 Modelos',
'Migración completa del sistema de evaluación a rix_runs_v2 con soporte para 6 modelos de IA independientes.',
E'## Pipeline V2 — Arquitectura Multi-Modelo\n\n### Cambio paradigmático\nEl sistema legacy evaluaba con 2 modelos en modo comparativo (ChatGPT vs Perplexity). El Pipeline V2 evalúa con **6 modelos independientes**, cada uno generando su propio score RIX:\n\n| Modelo | Provider | Característica clave |\n|---|---|---|\n| ChatGPT | OpenAI | Conocimiento amplio, consistencia |\n| Perplexity | Perplexity AI | Búsqueda en tiempo real |\n| Gemini | Google | Razonamiento multimodal |\n| DeepSeek | DeepSeek | Eficiencia y bajo coste |\n| Grok | xAI | Datos de X/Twitter en tiempo real |\n| Qwen | Alibaba | Perspectiva asiática, multilingual |\n\n### Tabla `rix_runs_v2`\nNueva tabla con estructura limpia:\n- `run_id`: Identificador único del run\n- `model_name`: Nombre del modelo\n- `rix_score`: Score final 0-100\n- `rix_score_adjusted`: Score ajustado (sin CXM si aplica)\n- Campos individuales para cada metacriterio (score + peso + categoría)\n- `batch_execution_date`: Fecha del barrido\n- `week_start`: Inicio de la semana evaluada\n\n### Edge Functions del Pipeline V2\n1. `rix-search-v2`: Búsqueda con cada modelo\n2. `rix-analyze-v2`: Análisis y scoring\n3. `rix-batch-orchestrator`: Orquestador de barridos masivos\n4. `sanitize-rix-insert`: Validación y limpieza de datos\n5. `rix-quality-watchdog`: Control de calidad post-barrido\n6. `rix-regression-analysis`: Detección de regresiones\n\n### Métricas del cambio\n- De 2 a 6 modelos por empresa\n- De evaluación comparativa a evaluación independiente\n- De ~500 registros/semana a ~1500 registros/semana\n- Nuevo campo `consensus_score` para medir acuerdo entre modelos',
'["Migración de 2 a 6 modelos de IA independientes","Nueva tabla rix_runs_v2 con estructura limpia","6 Edge Functions especializadas para el pipeline","Orquestador de barridos masivos (rix-batch-orchestrator)","Control de calidad automatizado (rix-quality-watchdog)","Detección de regresiones (rix-regression-analysis)","Soporte para Grok (xAI) y Qwen (Alibaba)"]'::jsonb,
'architecture', ARRAY['V2','pipeline','6-modelos','arquitectura'], '{"modelos": 6, "empresas_activas": 80, "registros_semana": 1500}'::jsonb, '2025-01-15'),

('3.1.0', 'Sistema de Barrido Automatizado',
'Orquestador inteligente de barridos con reintentos, colas de prioridad y monitorización en tiempo real.',
E'## Orquestador de Barridos\n\n### Edge Function `rix-batch-orchestrator`\nSistema completo de orquestación que gestiona:\n\n1. **Cola de prioridad**: Empresas se procesan por fase (1→2→3→4)\n2. **Reintentos inteligentes**: Hasta 3 reintentos con backoff exponencial\n3. **Paralelismo controlado**: Máximo de empresas simultáneas configurable\n4. **Monitorización**: Tabla `sweep_progress` con estado en tiempo real\n\n### Tablas de soporte\n- `sweep_progress`: Estado de cada empresa en el barrido\n- `pipeline_logs`: Logs detallados de cada paso\n- `pipeline_health_checks`: Verificaciones de salud post-barrido\n- `data_quality_reports`: Informes de calidad de datos\n\n### Panel Sweep Monitor (Admin)\n- Vista de barridos activos y completados\n- Progreso por empresa con porcentaje\n- Filtros por fase, estado, modelo\n- Acciones: reintentar, pausar, cancelar\n\n### CRONs configurados\n- Barrido semanal automático (lunes 02:00 UTC)\n- Actualización de estado de emisores (1º de cada mes)\n- Watchdog de calidad (post-barrido)',
'["Orquestador inteligente con cola de prioridad por fases","Reintentos automáticos con backoff exponencial","Monitorización en tiempo real con sweep_progress","Panel Sweep Monitor en admin con acciones","CRONs automáticos semanales y mensuales","Pipeline logs y health checks"]'::jsonb,
'feature', ARRAY['orquestador','barrido','automatización','CRON'], '{"empresas_activas": 80, "modelos": 6}'::jsonb, '2025-01-20'),

('3.2.0', 'Corporate Scraping con Firecrawl',
'Sistema de scraping de sitios web corporativos para enriquecer los datos de las empresas evaluadas.',
E'## Corporate Scraping\n\n### Motivación\nLos modelos de IA tienen conocimiento general, pero los sitios web corporativos contienen información actualizada que los modelos no siempre capturan: noticias recientes, cambios de directiva, nuevos productos, etc.\n\n### Arquitectura\n\n1. **`firecrawl-corporate-scrape`**: Edge Function que usa Firecrawl API para:\n   - Navegar el sitio web corporativo\n   - Extraer markdown limpio de las páginas\n   - Identificar noticias, equipo directivo, misión/visión\n   - Detectar sala de prensa e investor relations\n\n2. **`corporate-scrape-orchestrator`**: Orquesta el scraping de múltiples empresas:\n   - Cola de procesamiento por prioridad\n   - Rate limiting para respetar los sitios\n   - Reintentos con backoff\n\n### Tablas\n- `corporate_snapshots`: Datos extraídos (CEO, sede, empleados, descripción, etc.)\n- `corporate_news`: Noticias encontradas en sitios corporativos\n- `corporate_scrape_progress`: Estado del proceso de scraping\n\n### Datos extraídos\n- Descripción de la empresa\n- Equipo directivo (CEO, presidente, chairman)\n- Sede y país\n- Empleados aproximados\n- URL de sala de prensa e investor relations\n- Noticias corporativas recientes',
'["Integración con Firecrawl API para web scraping","Extracción automática de datos corporativos (CEO, sede, empleados)","Detección de noticias corporativas recientes","Orquestador con rate limiting y reintentos","Panel Corporate Scrape en admin","3 tablas nuevas: corporate_snapshots, corporate_news, corporate_scrape_progress"]'::jsonb,
'feature', ARRAY['scraping','Firecrawl','datos-corporativos'], '{"empresas_con_scrape": 50}'::jsonb, '2025-01-25'),

('3.3.0', 'Sistema de Leads y Cualificación',
'Pipeline completo de captación, cualificación y conversión de leads interesados.',
E'## Pipeline de Leads\n\n### Flujo completo\n\n1. **Captación**: Los usuarios no registrados que intentan acceder quedan como `interested_leads`\n2. **Cualificación automática**: Edge Function `send-qualification-form` envía formulario\n3. **Scoring**: `submit-qualification-form` calcula score basado en:\n   - Email corporativo (+20 puntos)\n   - Rol relevante (+15 puntos)\n   - Sectores de interés (+10 puntos por sector)\n   - Notas adicionales (+5 puntos)\n4. **Conversión**: Desde admin se puede convertir un lead en usuario con un click\n\n### Tablas\n- `interested_leads`: Leads captados con estado y scoring\n- `lead_qualification_responses`: Respuestas al formulario de cualificación\n\n### Panel InterestedLeadsPanel (Admin)\n- Lista de leads con estado y score\n- Acciones: cualificar, convertir, contactar\n- Filtros por estado y score\n- Métricas de conversión',
'["Pipeline completo de captación de leads","Formulario de cualificación automático","Scoring de leads por email corporativo, rol y sectores","Conversión directa desde admin a usuario registrado","Panel de leads en admin con métricas"]'::jsonb,
'feature', ARRAY['leads','cualificación','conversión','ventas'], '{}'::jsonb, '2025-01-28'),

('3.4.0', 'Newsroom Automatizada con IA',
'Sistema de generación automática de artículos de noticias basados en datos RIX.',
E'## Rix Press — Newsroom\n\n### Arquitectura\nSe implementó un sistema completo de generación de noticias:\n\n1. **`generate-news-story`**: Edge Function que:\n   - Analiza datos RIX de la semana\n   - Identifica las historias más relevantes (mayores cambios, mejores/peores scores)\n   - Genera artículos con formato periodístico profesional\n   - Incluye datos de verificación y fuentes\n\n2. **Tabla `news_articles`**:\n   - `headline`, `lead`, `body`: Contenido del artículo\n   - `slug`: URL amigable para SEO\n   - `chart_data`: Datos para gráficos inline\n   - `data_highlight`: Dato destacado\n   - `companies`: Empresas mencionadas\n   - `keywords`: Palabras clave para SEO\n\n3. **Tabla `weekly_news`**: Agrupación semanal de artículos\n\n### Páginas frontend\n- `/weekly-news`: Vista magazine con artículos de la semana\n- `/news/:slug`: Detalle de artículo con SEO completo\n- `/news-archive`: Archivo histórico de noticias\n\n### SEO\n- Meta tags dinámicos por artículo\n- JSON-LD para artículos\n- Sitemap automático\n- RSS feed',
'["Generación automática de artículos periodísticos con IA","Formato magazine profesional con datos verificados","SEO completo: meta tags, JSON-LD, sitemap, RSS","Vista semanal y archivo histórico de noticias","Gráficos inline en artículos","Edge Function generate-news-story"]'::jsonb,
'feature', ARRAY['newsroom','noticias','SEO','periodismo'], '{}'::jsonb, '2025-02-01'),

('3.5.0', 'Agente Comercial con IA',
'Sistema de inteligencia comercial para analizar conversaciones y detectar oportunidades de venta.',
E'## Sales Intelligence Agent\n\n### Propósito\nAnalizar las conversaciones del chat para:\n- Detectar interés comercial en empresas específicas\n- Identificar usuarios con perfil de comprador\n- Generar insights sobre qué empresas despiertan más interés\n\n### Edge Function `sales-intelligence-chat`\n- Chat especializado con contexto de ventas\n- Acceso a datos de conversaciones y perfiles\n- Genera recomendaciones de acción comercial\n\n### Panel SalesIntelligencePanel (Admin)\n- Chat con el agente comercial\n- Vista de oportunidades detectadas\n- Ranking de empresas más consultadas\n- Perfiles de usuarios con mayor potencial',
'["Agente comercial con IA en panel admin","Análisis de conversaciones para detectar oportunidades","Ranking de empresas más consultadas por usuarios","Edge Function sales-intelligence-chat","Panel dedicado en admin"]'::jsonb,
'feature', ARRAY['ventas','IA','comercial','admin'], '{}'::jsonb, '2025-02-03'),

('3.6.0', 'Rix Press Agent — Periodista Investigador',
'Agente de IA independiente especializado en análisis periodístico profundo usando Gemini 2.5 Pro.',
E'## Rix Press Agent\n\n### Motivación\nEl chat general (`chat-intelligence`) está optimizado para respuestas equilibradas y objetivas. Se necesitaba un modo especializado para análisis periodístico profundo que:\n- No tenga guardrails de reputación\n- Pueda ser más crítico y analítico\n- Use un modelo más potente (Gemini 2.5 Pro)\n- Acceda a todos los datos sin restricciones\n\n### Arquitectura\n\n**Edge Function `rix-press-agent`** (independiente de chat-intelligence):\n- Modelo: **Gemini 2.5 Pro** via `GOOGLE_GEMINI_API_KEY`\n- System prompt de periodista investigador senior\n- Acceso unificado a `rix_runs` + `rix_runs_v2`\n- Consulta al Vector Store (excluyendo sales_memento)\n- Streaming SSE compatible con frontend existente\n- Logging en `chat_intelligence_sessions` y `api_usage_logs`\n\n### Routing condicional en `ChatContext.tsx`\n```typescript\nconst edgeFunctionName = options?.pressMode \n  ? ''rix-press-agent'' \n  : ''chat-intelligence'';\n```\n\n### Acceso\n- Controlado por rol `press` en `user_roles`\n- Toggle en admin panel (`RixPressUsersPanel`)\n- Botón 📰 visible solo para usuarios con rol press\n\n### Capacidades del agente\n- Análisis sin restricciones de reputación\n- Investigación profunda con datos de 6 modelos\n- Formato periodístico profesional\n- Exportación a HTML con formato de informe',
'["Edge Function independiente rix-press-agent con Gemini 2.5 Pro","Routing condicional en ChatContext (pressMode)","Acceso controlado por rol press en user_roles","System prompt de periodista investigador senior","Acceso unificado a rix_runs + rix_runs_v2 + Vector Store","Streaming SSE compatible con frontend","Panel RixPressUsersPanel en admin para gestión de acceso"]'::jsonb,
'feature', ARRAY['rix-press','Gemini','periodismo','agente'], '{"modelos": 6, "registros_totales": 13690}'::jsonb, '2025-02-09'),

('3.7.0', 'Sistema de Snapshots de Plataforma',
'Registro histórico persistente de todas las evoluciones de la plataforma con detalle técnico completo.',
E'## Platform Snapshots\n\n### Motivación\nHasta ahora el historial de cambios estaba hardcodeado en `Admin.tsx` con solo 6 entradas. Se necesitaba un sistema persistente que:\n- Documente cada avance con detalle técnico completo\n- Sea editable y ampliable desde el admin\n- Sirva como memoria institucional del proyecto\n- Permita búsqueda y filtrado\n\n### Implementación\n\n**Tabla `platform_snapshots`**:\n- `version`: Semver (1.0.0, 2.0.0, 3.0.0...)\n- `title`: Título corto del hito\n- `summary`: Resumen en 1-2 frases\n- `detailed_description`: Markdown con arquitectura, decisiones, métricas\n- `changes`: Array JSON de cambios puntuales\n- `snapshot_type`: feature, improvement, fix, architecture, methodology, milestone\n- `tags`: Etiquetas para filtrar\n- `metrics_at_snapshot`: Métricas del momento\n\n**Componente `PlatformSnapshotsPanel`**:\n- Tabla con todas las snapshots ordenadas por fecha\n- Modal de detalle con Markdown renderizado\n- Formulario para crear nuevos snapshots\n- Filtros por tipo y búsqueda por texto\n\n**CRUD via admin-api**:\n- `list_snapshots`: Listar todas\n- `create_snapshot`: Crear nueva\n- `update_snapshot`: Editar existente\n- `delete_snapshot`: Eliminar',
'["Tabla platform_snapshots con RLS","~15 snapshots históricos como semilla","Panel PlatformSnapshotsPanel en admin","Modal de detalle con Markdown renderizado","Formulario de creación de snapshots","CRUD completo via admin-api","Filtros por tipo y búsqueda por texto"]'::jsonb,
'feature', ARRAY['snapshots','admin','documentación','historial'], '{"snapshots_iniciales": 16}'::jsonb, '2025-02-09');
