-- Seed rix_semantic_glossary with complete semantic dictionary
-- §1 Agrupaciones conceptuales
INSERT INTO rix_semantic_glossary (term, term_en, aliases, definition, category, repindex_relevance, related_metrics) VALUES
('grupos hospitalarios', 'hospital groups', '{"hospitales privados","sanidad privada","cadenas hospitalarias","redes hospitalarias","clínicas privadas grandes"}', 'Conjunto de empresas de sanidad privada: Quirónsalud, HM Hospitales, HLA Hospitales, Vithas, Viamed, Hospiten y Ribera Salud. Sector BBDD: Salud y Farmacéutico. Ninguna cotiza.', 'agrupacion', 'tickers:quironsalud,hm-hospitales,hla-hospitales,vithas,viamed,hospiten,ribera-salud|sector:Salud y Farmacéutico', '{"NVM","GAM","CEM"}'),
('Big Four', 'Big Four', '{"las cuatro grandes","big 4","auditoras","grandes consultoras","firmas de auditoría"}', 'Deloitte, PwC, EY y KPMG. Sector BBDD: Consultoría y Auditoría.', 'agrupacion', 'tickers:DELOITTE-PRIV,PWC-PRIV,EY-PRIV,KPMG-PRIV|sector:Consultoría y Auditoría', '{"NVM","GAM","DCM"}'),
('Big Tech', 'Big Tech', '{"las tecnológicas","gigantes tecnológicos","GAFAM","FAANG","las grandes de Silicon Valley"}', 'En nuestra BBDD: Amazon, Google/Alphabet y Meta. Sector: Telecomunicaciones y Tecnología, subsector Big Tech.', 'agrupacion', 'tickers:AMAZON-PRIV,GOOGLE-PRIV,META-PRIV|sector:Telecomunicaciones y Tecnología|subsector:Big Tech', '{"NVM","DCM","CXM"}'),
('grandes bancos', 'major banks', '{"banca española","los bancos","entidades financieras","sector bancario","bancos del IBEX"}', 'BBVA, Santander, CaixaBank, Sabadell, Bankinter, Unicaja. Sector: Banca y Servicios Financieros.', 'agrupacion', 'tickers:BBVA,SAN,CABK,SAB,BKT,UNI|sector:Banca y Servicios Financieros|subsector:Banca Comercial', '{"CXM","NVM","GAM","SIM"}'),
('constructoras', 'construction companies', '{"las constructoras","grandes constructoras","empresas de obra civil"}', 'ACS, Ferrovial, Acciona, Sacyr, FCC y OHLA. BBDD: sector Construcción e Infraestructuras + Construcción.', 'agrupacion', 'tickers:ACS,FER,ANA,SCYR,FCC-PRIV,OHL|sector:Construcción e Infraestructuras,Construcción', '{"NVM","CXM","GAM"}'),
('eléctricas', 'electric utilities', '{"las eléctricas","utilities","compañías eléctricas","empresas de luz","sector eléctrico"}', 'Iberdrola, Endesa, Naturgy, Enagás. Sector: Energía y Gas. Redeia si se menciona transporte.', 'agrupacion', 'tickers:IBE,ELE,NTGY,ENG,RED|sector:Energía y Gas|subsector:Utilities Eléctricas', '{"CXM","NVM","GAM","SIM"}'),
('renovables', 'renewables', '{"empresas renovables","verdes","energía solar","eólicas","fotovoltaicas","energía limpia"}', 'Acciona Energía, Audax, Berkeley, Ecoener, EiDF, Enerside, Grenergy, Solaria, Soltec. SOL y HLZ en Otros Sectores.', 'agrupacion', 'tickers:ANE,ADX,BKY,ECR,EIDF,ENS,GRE,SLR,SOL,HLZ|sector:Energía y Gas,Otros Sectores', '{"NVM","GAM","CXM"}'),
('farmacéuticas', 'pharmaceuticals', '{"farma","pharma","laboratorios","biotecnológicas"}', 'Almirall, Faes Farma, Grifols, Oryzon, PharmaMar, Rovi, Reig Jofre. ALM en Otros Sectores.', 'agrupacion', 'tickers:ALM,FAE,GRF,ORY,PHM,ROVI,RJF|sector:Salud y Farmacéutico,Otros Sectores', '{"NVM","DCM","CXM"}'),
('aseguradoras', 'insurance companies', '{"las aseguradoras","compañías de seguros","sector seguros"}', 'Mapfre, Catalana Occidente, Línea Directa en Banca y Servicios Financieros + Mutua Madrileña en Seguros.', 'agrupacion', 'tickers:MAP,CAT,LDA,MUTUA-PRIV|sector:Banca y Servicios Financieros,Seguros', '{"NVM","CXM","GAM"}'),
('inmobiliarias', 'real estate companies', '{"SOCIMIs","real estate","el ladrillo"}', 'No existe sector Inmobiliario en BBDD. Issuers repartidos entre Construcción e Infraestructuras y Otros Sectores.', 'agrupacion', 'tickers:AED,AIRON,ARM,CAST,CEVA,COL,IDEALISTA-PRIV,INSUR,LRE,LIB7,MRL,MVC,MTB,HOME,NYE,RLIA,REN,UPH,URB', '{"CXM","NVM"}'),
('promotoras inmobiliarias', 'real estate developers', '{"promotoras","promotoras de vivienda"}', 'AEDAS Homes, Neinor Homes, Metrovacesa y Urbas.', 'agrupacion', 'tickers:AED,HOME,MVC,URB', '{"CXM","NVM"}'),
('supermercados', 'supermarkets', '{"distribución alimentaria","cadenas de alimentación"}', 'Mercadona, Eroski en Distribución + DIA en Otros Sectores.', 'agrupacion', 'tickers:MERC-PRIV,EROSKI-PRIV,DIA|sector:Distribución,Otros Sectores', '{"NVM","DCM"}'),
('medios de comunicación', 'media companies', '{"medios","prensa","televisiones","cadenas de televisión","grupos mediáticos"}', 'Atresmedia, MFE, PRISA, Secuoya, Squirrel, Vocento. Todos en Otros Sectores excepto Secuoya.', 'agrupacion', 'tickers:A3M,MFEB,PRS,SEC,SQM,VOC|sector:Otros Sectores,Telecomunicaciones y Tecnología', '{"NVM","DCM","CEM"}'),
('telecos', 'telecoms', '{"operadoras","empresas de telecomunicaciones"}', 'Telefónica, Cellnex, MASORANGE, Parlem, Ezentis. Repartidos entre varios sectores.', 'agrupacion', 'tickers:TEF,CLNX,MASOR-PRIV,PAR,EZE|sector:Telecomunicaciones y Tecnología,Telecomunicaciones,Otros Sectores', '{"NVM","DCM","CXM"}'),
('cerveceras', 'breweries', '{"empresas de cerveza"}', 'Damm y Mahou San Miguel. Sector: Alimentación.', 'agrupacion', 'tickers:DAMM-PRIV,MAHOU-PRIV|sector:Alimentación', '{"NVM","DCM"}'),
('bodegas', 'wineries', '{"empresas de vino","sector vinícola"}', 'Bodegas Bilbaínas, Riojanas en Otros Sectores + Freixenet en Alimentación.', 'agrupacion', 'tickers:BIL,RIO,FREIX-PRIV|sector:Otros Sectores,Alimentación', '{"NVM","DCM"}'),
('siderúrgicas', 'steelmakers', '{"acereras","metalúrgicas"}', 'Acerinox, ArcelorMittal, Lingotes Especiales, Tubacex, Tubos Reunidos. Sector: Materias Primas y Siderurgia.', 'agrupacion', 'tickers:ACX,MTS,LES,TUB,TRG|sector:Materias Primas y Siderurgia', '{"NVM","CXM"}'),
('sector defensa', 'defense sector', '{"defensa","industria militar","armamento"}', 'Airbus, Prosegur, Prosegur Cash en Otros Sectores + Indra, Amper, Escribano en Telecomunicaciones y Tecnología.', 'agrupacion', 'tickers:AIR,PSG,CASH,IDR,AMP,EME-PRIV|sector:Otros Sectores,Telecomunicaciones y Tecnología', '{"NVM","GAM","CEM"}'),
('empresas de moda y lujo', 'fashion and luxury', '{"moda","lujo","textil"}', 'Inditex, Puig, Adolfo Domínguez, Nextil. Moda y Distribución + Otros Sectores.', 'agrupacion', 'tickers:ITX,PUIG,ADZ,NXT|sector:Moda y Distribución,Otros Sectores', '{"NVM","DCM","CXM"}'),
('petroleras', 'oil companies', '{"oil and gas","hidrocarburos"}', 'Repsol en Energía y Gas + Exolum y Moeve en Petróleo y Energía.', 'agrupacion', 'tickers:REP,EXOLUM-PRIV,moeve|sector:Energía y Gas,Petróleo y Energía', '{"CXM","NVM","SIM"}'),
('OTAs', 'OTAs', '{"agencias online","plataformas de viaje","agencias de viajes online"}', 'Booking.com, eDreams ODIGEO, Airbnb. Sector: Hoteles y Turismo.', 'agrupacion', 'tickers:BOOKING-PRIV,EDR,AIRBNB-PRIV|sector:Hoteles y Turismo', '{"NVM","DCM","CXM"}'),

-- §2 Marcas comerciales → empresa matriz
('Zara', 'Zara', '{"Massimo Dutti","Pull & Bear","Bershka","Stradivarius","Oysho","Zara Home"}', 'Marca de Inditex (ITX). RepIndex analiza a nivel macro-corporate. Para marcas individuales existe MediaMetrics.', 'marca_matriz', 'ticker:ITX|issuer:inditex', '{"NVM","DCM"}'),
('Movistar', 'Movistar', '{"O2","Vivo"}', 'Marca de Telefónica (TEF).', 'marca_matriz', 'ticker:TEF|issuer:telefonica', '{"NVM","DCM"}'),
('Antena 3', 'Antena 3', '{"laSexta","Onda Cero"}', 'Marcas de Atresmedia (A3M).', 'marca_matriz', 'ticker:A3M|issuer:atresmedia', '{"NVM","DCM"}'),
('Telecinco', 'Telecinco', '{"Cuatro","Boing"}', 'Marcas de MFE-MediaForEurope (MFEB).', 'marca_matriz', 'ticker:MFEB|issuer:mfe-mediaforeurope', '{"NVM","DCM"}'),
('El País', 'El País', '{"Cadena SER","AS","Cinco Días"}', 'Marcas de PRISA (PRS).', 'marca_matriz', 'ticker:PRS|issuer:prisa', '{"NVM","DCM"}'),
('ABC periódico', 'ABC newspaper', '{}', 'Marca de Vocento (VOC).', 'marca_matriz', 'ticker:VOC|issuer:vocento', '{"NVM","DCM"}'),
('Iberia', 'Iberia', '{"Vueling","British Airways","Aer Lingus","Level"}', 'Marcas de IAG (IAG).', 'marca_matriz', 'ticker:IAG|issuer:iag', '{"NVM","DCM","CXM"}'),
('Estrella Damm', 'Estrella Damm', '{"Voll-Damm"}', 'Marcas de Damm. Estrella Galicia NO es Damm (Hijos de Rivera, no en BBDD).', 'marca_matriz', 'ticker:DAMM-PRIV|issuer:damm', '{"NVM","DCM"}'),
('Mahou', 'Mahou', '{"San Miguel cerveza","Alhambra cerveza"}', 'Marcas de Mahou San Miguel.', 'marca_matriz', 'ticker:MAHOU-PRIV|issuer:mahou-san-miguel', '{"NVM","DCM"}'),
('Carbonell', 'Carbonell', '{"Koipe"}', 'Marcas de Deoleo (OLE).', 'marca_matriz', 'ticker:OLE|issuer:deoleo', '{"NVM","DCM"}'),
('Hacendado', 'Hacendado', '{"Deliplus","Bosque Verde","Compy"}', 'Marcas de Mercadona.', 'marca_matriz', 'ticker:MERC-PRIV|issuer:mercadona', '{"NVM","DCM"}'),
('Hipercor', 'Hipercor', '{"Supercor","Opencor"}', 'Marcas de El Corte Inglés.', 'marca_matriz', 'ticker:ECI-PRIV|issuer:el-corte-ingles', '{"NVM","DCM"}'),
('Silestone', 'Silestone', '{"Dekton"}', 'Marcas de Cosentino.', 'marca_matriz', 'ticker:COSENT-PRIV|issuer:cosentino', '{"NVM","DCM"}'),
('Orange España', 'Orange Spain', '{"Jazztel marca","Yoigo","Pepephone","Simyo"}', 'Marcas de MASORANGE.', 'marca_matriz', 'ticker:MASOR-PRIV|issuer:masorange', '{"NVM","DCM"}'),
('Carolina Herrera', 'Carolina Herrera', '{"Paco Rabanne","Jean Paul Gaultier","Nina Ricci"}', 'Marcas de Puig (PUIG).', 'marca_matriz', 'ticker:PUIG|issuer:puig', '{"NVM","DCM"}'),
('Facebook', 'Facebook', '{"Instagram","WhatsApp"}', 'Marcas de Meta.', 'marca_matriz', 'ticker:META-PRIV|issuer:meta', '{"NVM","DCM"}'),
('YouTube', 'YouTube', '{"Gmail","Google Maps","Google Cloud"}', 'Marcas de Google/Alphabet.', 'marca_matriz', 'ticker:GOOGLE-PRIV|issuer:google', '{"NVM","DCM"}'),
('AWS', 'AWS', '{"Amazon Web Services","Prime Video","Alexa"}', 'Marcas de Amazon.', 'marca_matriz', 'ticker:AMAZON-PRIV|issuer:amazon', '{"NVM","DCM"}'),
('Freixenet marca', 'Freixenet brand', '{"Segura Viudas"}', 'Marcas de Freixenet.', 'marca_matriz', 'ticker:FREIX-PRIV|issuer:freixenet', '{"NVM","DCM"}'),
('Sanitas marca', 'Sanitas brand', '{"Sanitas Seguros","Sanitas Dental","Hospitales Sanitas","Sanitas Mayores"}', 'Filial del grupo británico Bupa.', 'marca_matriz', 'ticker:sanitas|issuer:sanitas', '{"NVM","DCM","GAM"}'),
('Correos marca', 'Correos brand', '{"Correos Express"}', 'Marcas de Correos.', 'marca_matriz', 'ticker:CORREOS-PRIV|issuer:correos', '{"NVM","DCM"}'),

-- §3 Nombres anteriores e históricos
('Cepsa', 'Cepsa', '{}', 'Ahora es Moeve (moeve). Rebrand completado 2025-2026.', 'nombre_historico', 'ticker:moeve|issuer:moeve', NULL),
('Gas Natural', 'Gas Natural', '{"Gas Natural Fenosa"}', 'Ahora es Naturgy Energy Group (NTGY).', 'nombre_historico', 'ticker:NTGY|issuer:naturgy', NULL),
('Red Eléctrica de España', 'Red Eléctrica de España', '{"REE","Red Eléctrica"}', 'Ahora es Redeia Corporación (RED).', 'nombre_historico', 'ticker:RED|issuer:redeia', NULL),
('OHL nombre', NULL, '{"Obrascón Huarte Lain"}', 'Ahora es OHLA. Issuer_id: OHL.', 'nombre_historico', 'ticker:OHL|issuer:ohla', NULL),
('CLH', NULL, '{"Compañía Logística de Hidrocarburos"}', 'Ahora es Exolum.', 'nombre_historico', 'ticker:EXOLUM-PRIV|issuer:exolum', NULL),
('Bankia', NULL, '{}', 'Absorbida por CaixaBank (CABK) en 2021.', 'nombre_historico', 'ticker:CABK|issuer:caixabank', NULL),
('Liberbank', NULL, '{}', 'Absorbida por Unicaja (UNI) en 2021.', 'nombre_historico', 'ticker:UNI|issuer:unicaja', NULL),
('Jazztel empresa', NULL, '{}', 'Absorbida, ahora parte de MASORANGE.', 'nombre_historico', 'ticker:MASOR-PRIV|issuer:masorange', NULL),
('MásMóvil', NULL, '{}', 'Fusionado con Orange para formar MASORANGE.', 'nombre_historico', 'ticker:MASOR-PRIV|issuer:masorange', NULL),
('Sol Meliá', NULL, '{}', 'Ahora es Meliá Hotels International (MEL).', 'nombre_historico', 'ticker:MEL|issuer:melia', NULL),
('Food Delivery Brands', NULL, '{}', 'Nombre corporativo de Telepizza Brands (TPZ).', 'nombre_historico', 'ticker:TPZ|issuer:telepizza', NULL),
('Grupo Catalana Occidente', NULL, '{}', 'Rebrand a GCO en 2024. Issuer_id: CAT.', 'nombre_historico', 'ticker:CAT|issuer:catalana-occidente', NULL),

-- §4 Acrónimos conceptuales
('IBEX 35 índice', 'IBEX 35 index', '{"IBEX","IBEX35","ibex 35"}', 'Índice bursátil principal español. Filtrar por ibex_family_category = IBEX 35.', 'acronimo', 'filter:ibex_family_category=IBEX 35', '{"CXM"}'),
('BME concepto', 'BME concept', '{}', 'Bolsas y Mercados Españoles, operador del mercado.', 'acronimo', NULL, '{"CXM"}'),
('CNMV concepto', NULL, '{}', 'Comisión Nacional del Mercado de Valores. Regulador.', 'acronimo', NULL, '{"GAM","SIM","CEM"}'),
('SOCIMI concepto', 'REIT', '{}', 'Sociedad cotizada de inversión inmobiliaria. Resolver a issuer_ids de inmobiliarias.', 'acronimo', 'tickers:AED,AIRON,ARM,CAST,CEVA,COL,INSUR,LRE,LIB7,MRL,MVC,MTB,HOME,NYE,RLIA,REN,UPH,URB', '{"CXM","NVM"}'),
('OPA concepto', 'Takeover bid', '{"oferta pública de adquisición"}', 'Oferta pública para adquirir participación mayoritaria.', 'acronimo', NULL, '{"CXM","CEM","GAM"}'),
('OPV concepto', 'IPO concept', '{"oferta pública de venta","salida a bolsa concepto"}', 'Primera venta pública de acciones.', 'acronimo', NULL, '{"CXM","NVM"}'),
('ESG concepto acrónimo', 'ESG acronym', '{}', 'Criterios medioambientales, sociales y de gobernanza.', 'acronimo', NULL, '{"GAM","NVM","CEM"}'),
('GEO acrónimo', 'GEO acronym', '{"Generative Engine Optimization"}', 'Optimización para motores generativos.', 'acronimo', NULL, '{"NVM","DCM"}'),
('AEO acrónimo', 'AEO acronym', '{"Answer Engine Optimization"}', 'Optimización para motores de respuesta.', 'acronimo', NULL, '{"NVM","DCM"}'),
('LLMO acrónimo', 'LLMO acronym', '{"Large Language Model Optimization"}', 'Optimización para modelos de lenguaje grandes.', 'acronimo', NULL, '{"NVM","DCM"}'),
('RIX índice', 'RIX index', '{}', 'Índice propietario de RepIndex.', 'acronimo', NULL, '{"NVM","DRM","SIM","RMM","CEM","GAM","DCM","CXM"}'),

-- §5 Términos sectoriales coloquiales
('salud sector', 'healthcare sector', '{"farma sector","hospitales sector","sanidad","healthcare","biotech"}', 'Buscar en Salud y Farmacéutico. Incluir ALM de Otros Sectores.', 'sector_coloquial', 'sector:Salud y Farmacéutico|extra_tickers:ALM', '{"NVM","DCM"}'),
('banca sector', 'banking sector', '{"bancos sector","financiero","finanzas","banking"}', 'Buscar en Banca y Servicios Financieros.', 'sector_coloquial', 'sector:Banca y Servicios Financieros', '{"CXM","NVM","GAM","SIM"}'),
('seguros sector', 'insurance sector', '{"aseguradoras sector","insurance"}', 'Banca y Servicios Financieros + sector Seguros.', 'sector_coloquial', 'sector:Banca y Servicios Financieros,Seguros|extra_tickers:MAP,CAT,LDA,MUTUA-PRIV', '{"NVM","CXM","GAM"}'),
('energía sector', 'energy sector', '{"eléctricas sector","utilities sector","gas sector"}', 'Energía y Gas + Petróleo y Energía. Incluir HLZ y SOL.', 'sector_coloquial', 'sector:Energía y Gas,Petróleo y Energía,Otros Sectores|extra_tickers:HLZ,SOL,EXOLUM-PRIV,moeve', '{"CXM","NVM","GAM"}'),
('construcción sector', 'construction sector', '{"obra civil sector"}', 'Construcción e Infraestructuras + Construcción.', 'sector_coloquial', 'sector:Construcción e Infraestructuras,Construcción', '{"NVM","CXM","GAM"}'),
('inmobiliario sector', 'real estate sector', '{"real estate sector","SOCIMIs sector","ladrillo sector","vivienda sector"}', 'No existe sector en BBDD. Resolver por issuer_ids directos.', 'sector_coloquial', 'tickers:AED,AIRON,ARM,CAST,CEVA,COL,IDEALISTA-PRIV,INSUR,LRE,LIB7,MRL,MVC,MTB,HOME,NYE,RLIA,REN,UPH,URB', '{"CXM","NVM"}'),
('tecnología sector', 'technology sector', '{"tech sector","software sector","IT sector","digital sector","IA sector","AI sector"}', 'Telecomunicaciones y Tecnología excluyendo telecos. Incluir SER y ROBOT.', 'sector_coloquial', 'sector:Telecomunicaciones y Tecnología|extra_tickers:SER,ROBOT', '{"NVM","DCM","CXM"}'),
('telecomunicaciones sector', 'telecom sector', '{"operadoras sector"}', 'TEF, CLNX, PAR + MASOR-PRIV + EZE.', 'sector_coloquial', 'tickers:TEF,CLNX,PAR,MASOR-PRIV,EZE', '{"NVM","DCM","CXM"}'),
('medios sector', 'media sector', '{"media sector","prensa sector","televisión sector","TV sector","entretenimiento sector","audiovisual sector"}', 'No hay sector Media en BBDD. Resolver por issuer_ids.', 'sector_coloquial', 'tickers:A3M,MFEB,PRS,SQM,VOC,SEC', '{"NVM","DCM","CEM"}'),
('moda sector', 'fashion sector', '{"fashion sector","textil sector","lujo sector","fragancias sector"}', 'Moda y Distribución (ITX, ADZ). Incluir PUIG y NXT.', 'sector_coloquial', 'sector:Moda y Distribución|extra_tickers:PUIG,NXT|exclude_tickers:ECI-PRIV,PRIM', '{"NVM","DCM","CXM"}'),
('retail sector', 'retail sector', '{"distribución sector","supermercados sector"}', 'Distribución + ECI-PRIV + DIA.', 'sector_coloquial', 'sector:Distribución|extra_tickers:ECI-PRIV,DIA', '{"NVM","DCM"}'),
('turismo sector', 'tourism sector', '{"transporte sector","aviación sector","hoteles sector","travel sector"}', 'Hoteles y Turismo. Incluir Renfe.', 'sector_coloquial', 'sector:Hoteles y Turismo,Transporte|extra_tickers:RENFE-PRIV', '{"NVM","DCM","CXM"}'),
('alimentación sector', 'food sector', '{"bebidas sector","food sector","comida sector"}', 'Alimentación. Incluir EBR, CCEP, OLE, NHS, BIL, RIO, PVA.', 'sector_coloquial', 'sector:Alimentación|extra_tickers:EBR,CCEP,OLE,NHS,BIL,RIO,PVA', '{"NVM","DCM"}'),
('automoción sector', 'automotive sector', '{"automóvil sector","automotive sector","coches sector"}', 'Automoción. Incluir CIE, GEST, AZK.', 'sector_coloquial', 'sector:Automoción|extra_tickers:CIE,GEST,AZK', '{"NVM","DCM","CXM"}'),
('defensa sector coloquial', 'defense sector colloquial', '{"seguridad sector","militar sector"}', 'No hay sector Defensa en BBDD. Resolver por issuer_ids.', 'sector_coloquial', 'tickers:AIR,PSG,CASH,IDR,AMP,EME-PRIV', '{"NVM","GAM","CEM"}'),
('siderurgia sector', 'steelmaking sector', '{"acero sector","materias primas sector","metalurgia sector"}', 'Materias Primas y Siderurgia.', 'sector_coloquial', 'sector:Materias Primas y Siderurgia', '{"NVM","CXM"}'),
('logística sector', 'logistics sector', '{"paquetería sector","mensajería sector","envíos sector"}', 'Logística + Logista de Otros Sectores.', 'sector_coloquial', 'sector:Logística|extra_tickers:LOG', '{"NVM","DCM"}'),
('consultoría sector', 'consulting sector', '{"auditoría sector","servicios profesionales sector"}', 'Consultoría y Auditoría. Incluir LLYC y APPS.', 'sector_coloquial', 'sector:Consultoría y Auditoría|extra_tickers:LLYC,APPS', '{"NVM","GAM","DCM"}'),
('restauración sector', 'restaurant sector', '{"fast food sector","comida rápida sector"}', 'Restauración + TPZ.', 'sector_coloquial', 'sector:Restauración|extra_tickers:TPZ', '{"NVM","DCM"}'),
('industria sector', 'industry sector', '{"industrial sector"}', 'Industria. Incluir FDR, GAM, NEA, MDF.', 'sector_coloquial', 'sector:Industria|extra_tickers:FDR,GAM,NEA,MDF', '{"NVM","DCM"}'),

-- §6 Filtros conceptuales
('empresas cotizadas', 'listed companies', '{"cotizadas","empresas que cotizan","listadas en bolsa"}', 'Filtrar por cotiza_en_bolsa = true.', 'filtro', 'filter:cotiza_en_bolsa=true', NULL),
('empresas privadas', 'private companies', '{"no cotizadas","empresas que no cotizan"}', 'Filtrar por cotiza_en_bolsa = false.', 'filtro', 'filter:cotiza_en_bolsa=false', NULL),
('IBEX Medium Cap filtro', 'IBEX Medium Cap filter', '{"mid caps"}', 'Filtrar por ibex_family_category = IBEX Medium Cap.', 'filtro', 'filter:ibex_family_category=IBEX Medium Cap', '{"CXM"}'),
('IBEX Small Cap filtro', 'IBEX Small Cap filter', '{"small caps"}', 'Filtrar por ibex_family_category = IBEX Small Cap.', 'filtro', 'filter:ibex_family_category=IBEX Small Cap', '{"CXM"}'),
('BME Growth filtro', 'BME Growth filter', '{"growth"}', 'Filtrar por ibex_family_category que contenga BME Growth.', 'filtro', 'filter:ibex_family_category~BME Growth', '{"CXM"}'),
('Mercado Continuo filtro', 'Continuous Market filter', '{}', 'Filtrar por ibex_family_category que contenga Mercado Continuo.', 'filtro', 'filter:ibex_family_category~Mercado Continuo', '{"CXM"}'),
('chicharros', 'penny stocks', '{}', 'Empresas pequeñas y volátiles. IBEX Small Cap o BME Growth.', 'filtro', 'filter:ibex_family_category=IBEX Small Cap,BME Growth', '{"CXM"}'),

-- §7 Personas → empresa (IBEX 35)
('Marc Murtra', NULL, '{}', 'Presidente ejecutivo de Telefónica (TEF) desde enero 2025.', 'persona_empresa', 'ticker:TEF|issuer:telefonica', '{"NVM","GAM"}'),
('Ángel Escribano', NULL, '{}', 'Presidente ejecutivo de Indra (IDR) desde enero 2025. Fundador de EM&E.', 'persona_empresa', 'ticker:IDR|issuer:indra|also:EME-PRIV', '{"NVM","GAM"}'),
('Ana Botín', NULL, '{}', 'Presidenta ejecutiva de Banco Santander (SAN).', 'persona_empresa', 'ticker:SAN|issuer:santander', '{"NVM","GAM"}'),
('Carlos Torres Vila', NULL, '{}', 'Presidente ejecutivo de BBVA.', 'persona_empresa', 'ticker:BBVA|issuer:bbva', '{"NVM","GAM"}'),
('José Ignacio Goirigolzarri', NULL, '{"Goirigolzarri"}', 'Presidente de CaixaBank (CABK).', 'persona_empresa', 'ticker:CABK|issuer:caixabank', '{"NVM","GAM"}'),
('Ignacio Sánchez Galán', NULL, '{"Sánchez Galán"}', 'Presidente ejecutivo de Iberdrola (IBE).', 'persona_empresa', 'ticker:IBE|issuer:iberdrola', '{"NVM","GAM","CXM"}'),
('Florentino Pérez', NULL, '{"Florentino"}', 'Presidente de ACS. En contexto futbolístico es Real Madrid, no ACS.', 'persona_empresa', 'ticker:ACS|issuer:acs', '{"NVM","GAM"}'),
('José Manuel Entrecanales', NULL, '{"Entrecanales"}', 'Presidente y CEO de Acciona (ANA).', 'persona_empresa', 'ticker:ANA|issuer:acciona', '{"NVM","GAM"}'),
('Rafael del Pino', NULL, '{"Del Pino"}', 'Presidente de Ferrovial (FER).', 'persona_empresa', 'ticker:FER|issuer:ferrovial', '{"NVM","GAM"}'),
('Manuel Manrique', NULL, '{}', 'Presidente y CEO de Sacyr (SCYR).', 'persona_empresa', 'ticker:SCYR|issuer:sacyr', '{"NVM","GAM"}'),
('Francisco Reynés', NULL, '{"Reynés"}', 'Presidente y CEO de Naturgy (NTGY).', 'persona_empresa', 'ticker:NTGY|issuer:naturgy', '{"NVM","GAM"}'),
('Marc Puig persona', NULL, '{}', 'Presidente ejecutivo de Puig Brands (PUIG).', 'persona_empresa', 'ticker:PUIG|issuer:puig', '{"NVM","GAM"}'),
('Marta Ortega', NULL, '{}', 'Presidenta de Inditex (ITX).', 'persona_empresa', 'ticker:ITX|issuer:inditex', '{"NVM","GAM"}'),
('Óscar García Maceiras', NULL, '{"García Maceiras"}', 'Consejero delegado de Inditex (ITX).', 'persona_empresa', 'ticker:ITX|issuer:inditex', '{"NVM","GAM"}'),
('Antonio Huertas', NULL, '{}', 'Presidente y CEO de Mapfre (MAP).', 'persona_empresa', 'ticker:MAP|issuer:mapfre', '{"NVM","GAM"}'),
('María Dolores Dancausa', NULL, '{"Dancausa"}', 'Consejera delegada de Bankinter (BKT).', 'persona_empresa', 'ticker:BKT|issuer:bankinter', '{"NVM","GAM"}'),
('Josep Oliu', NULL, '{"Oliu"}', 'Presidente de Banco Sabadell (SAB).', 'persona_empresa', 'ticker:SAB|issuer:sabadell', '{"NVM","GAM"}'),
('Gabriel Escarrer', NULL, '{"Escarrer"}', 'Familia fundadora de Meliá Hotels (MEL).', 'persona_empresa', 'ticker:MEL|issuer:melia', '{"NVM","GAM"}'),
('Tobías Martínez', NULL, '{}', 'Consejero delegado de Cellnex (CLNX).', 'persona_empresa', 'ticker:CLNX|issuer:cellnex', '{"NVM","GAM"}'),
('Mauricio Lucena', NULL, '{}', 'Presidente y CEO de Aena (AENA).', 'persona_empresa', 'ticker:AENA|issuer:aena', '{"NVM","GAM"}'),
('Juan López-Belmonte', NULL, '{"López-Belmonte"}', 'Presidente y CEO de Rovi (ROVI).', 'persona_empresa', 'ticker:ROVI|issuer:rovi', '{"NVM","GAM"}'),
('Isidro Fainé', NULL, '{"Fainé"}', 'Presidente de Fundación La Caixa y CriteriaCaixa, primer accionista de CaixaBank.', 'persona_empresa', 'ticker:CABK|issuer:caixabank', '{"NVM","GAM"}'),
('Thomas Glanzmann', NULL, '{"Glanzmann"}', 'Expresidente de Grifols (GRF).', 'persona_empresa', 'ticker:GRF|issuer:grifols', '{"NVM","GAM"}'),
('Steven Mayer', NULL, '{}', 'Primer directivo externo a la familia Grifols en Grifols (GRF).', 'persona_empresa', 'ticker:GRF|issuer:grifols', '{"NVM","GAM"}'),
('Maarten Wetselaar', NULL, '{"Wetselaar"}', 'CEO de Moeve (antigua Cepsa).', 'persona_empresa', 'ticker:moeve|issuer:moeve', '{"NVM","GAM"}'),
('Amancio Ortega', NULL, '{"la empresa de Amancio"}', 'Fundador de Inditex (ITX).', 'persona_empresa', 'ticker:ITX|issuer:inditex', '{"NVM","GAM","CXM"}'),
('Juan Roig', NULL, '{"la empresa de Juan Roig"}', 'Presidente de Mercadona.', 'persona_empresa', 'ticker:MERC-PRIV|issuer:mercadona', '{"NVM","GAM"}'),
('Demetrio Carceller', NULL, '{"Carceller"}', 'Presidente de Damm.', 'persona_empresa', 'ticker:DAMM-PRIV|issuer:damm', '{"NVM","GAM"}'),
('Víctor del Pozo', NULL, '{"Del Pozo"}', 'Consejero delegado de El Corte Inglés.', 'persona_empresa', 'ticker:ECI-PRIV|issuer:el-corte-ingles', '{"NVM","GAM"}'),
('Marta Álvarez', NULL, '{}', 'Presidenta de El Corte Inglés.', 'persona_empresa', 'ticker:ECI-PRIV|issuer:el-corte-ingles', '{"NVM","GAM"}'),
('Sundar Pichai', NULL, '{"Pichai"}', 'CEO de Google/Alphabet.', 'persona_empresa', 'ticker:GOOGLE-PRIV|issuer:google', '{"NVM","GAM"}'),
('Mark Zuckerberg', NULL, '{"Zuckerberg","la empresa de Zuckerberg"}', 'CEO de Meta.', 'persona_empresa', 'ticker:META-PRIV|issuer:meta', '{"NVM","GAM"}'),
('Andy Jassy', NULL, '{"Jassy"}', 'CEO de Amazon.', 'persona_empresa', 'ticker:AMAZON-PRIV|issuer:amazon', '{"NVM","GAM"}'),
('Jeff Bezos', NULL, '{"Bezos"}', 'Fundador de Amazon.', 'persona_empresa', 'ticker:AMAZON-PRIV|issuer:amazon', '{"NVM","GAM"}'),
('Tim Cook', NULL, '{"Cook"}', 'CEO de Apple. NOTA: Apple NO está en la BBDD de RepIndex.', 'persona_empresa', 'no_disponible:Apple no está en BBDD', NULL),
('Satya Nadella', NULL, '{"Nadella"}', 'CEO de Microsoft. NOTA: Microsoft NO está en la BBDD.', 'persona_empresa', 'no_disponible:Microsoft no está en BBDD', NULL),
('Sam Altman', NULL, '{"Altman"}', 'CEO de OpenAI. NOTA: OpenAI NO está en la BBDD.', 'persona_empresa', 'no_disponible:OpenAI no está en BBDD', NULL),
('Elon Musk', NULL, '{"Musk"}', 'CEO de Tesla/X. NOTA: Ni Tesla ni X están en la BBDD.', 'persona_empresa', 'no_disponible:Tesla/X no están en BBDD', NULL),

-- §8 Relaciones de propiedad
('Quirónsalud propiedad', NULL, '{"de quién es Quirónsalud","matriz de Quirónsalud"}', 'Propiedad de Fresenius (Helios). Mayor grupo hospitalario privado de España.', 'propiedad', 'ticker:quironsalud|matriz:Fresenius', '{"NVM","GAM"}'),
('Sanitas propiedad', NULL, '{"de quién es Sanitas","matriz de Sanitas"}', 'Filial de Bupa (UK). No cotiza.', 'propiedad', 'ticker:sanitas|matriz:Bupa', '{"NVM","GAM"}'),
('Ribera Salud propiedad', NULL, '{"de quién es Ribera Salud"}', 'Propiedad de Vivalto Santé (Francia).', 'propiedad', 'ticker:ribera-salud|matriz:Vivalto Santé', '{"NVM","GAM"}'),
('HLA Hospitales propiedad', NULL, '{"de quién es HLA"}', 'Pertenece a Grupo ASISA (cooperativa Lavinia).', 'propiedad', 'ticker:hla-hospitales|matriz:ASISA', '{"NVM","GAM"}'),
('Campofrío propiedad', NULL, '{"de quién es Campofrío"}', 'Pertenece a Sigma Food Group (México).', 'propiedad', 'ticker:CAMPO-PRIV|matriz:Sigma Food Group', '{"NVM","GAM"}'),
('MASORANGE propiedad', NULL, '{"de quién es MASORANGE"}', 'Fusión Orange España + MásMóvil.', 'propiedad', 'ticker:MASOR-PRIV', '{"NVM","GAM"}'),
('Acciona Energía propiedad', NULL, '{"de quién es Acciona Energía"}', 'Filial cotizada de Acciona (ANA). Dos issuers independientes.', 'propiedad', 'ticker:ANE|matriz_ticker:ANA', '{"NVM","GAM","CXM"}'),
('Prosegur Cash propiedad', NULL, '{"de quién es Prosegur Cash"}', 'Filial cotizada de Prosegur (PSG). Dos issuers independientes.', 'propiedad', 'ticker:CASH|matriz_ticker:PSG', '{"NVM","GAM"}'),
('Moeve propiedad', NULL, '{"de quién es Moeve","de quién es Cepsa"}', 'Antigua Cepsa. Controlada por Mubadala y Carlyle.', 'propiedad', 'ticker:moeve|matriz:Mubadala/Carlyle', '{"NVM","GAM","CXM"}'),
('Coca-Cola EP propiedad', NULL, '{"de quién es Coca-Cola Europacific"}', 'Embotellador europeo, no es The Coca-Cola Company.', 'propiedad', 'ticker:CCEP', '{"NVM","GAM"}'),

-- Apéndice B: No disponibles
('Abengoa', NULL, '{}', 'No está en la BBDD. En proceso de liquidación.', 'no_disponible', 'motivo:en liquidación', NULL),
('Banco Popular', NULL, '{}', 'Absorbido por Santander (SAN) en 2017.', 'no_disponible', 'motivo:absorbido por Santander|sugerencia_ticker:SAN', NULL),
('Hijos de Rivera', NULL, '{"Estrella Galicia"}', 'No está en la BBDD. No confundir con Damm/Estrella Damm.', 'no_disponible', 'motivo:no monitorizada', NULL),
('Lidl', NULL, '{}', 'No está en la BBDD. Cadena extranjera.', 'no_disponible', 'motivo:cadena extranjera', NULL),
('Carrefour', NULL, '{}', 'No está en la BBDD. Cadena extranjera.', 'no_disponible', 'motivo:cadena extranjera', NULL),
('Aldi', NULL, '{}', 'No está en la BBDD. Cadena extranjera.', 'no_disponible', 'motivo:cadena extranjera', NULL),
('Calidad Pascual', NULL, '{"Pascual"}', 'No está en la BBDD.', 'no_disponible', 'motivo:no monitorizada', NULL),
('Danone', NULL, '{}', 'No está en la BBDD.', 'no_disponible', 'motivo:no monitorizada', NULL),
('El Pozo', NULL, '{"Grupo Fuertes"}', 'No está en la BBDD.', 'no_disponible', 'motivo:no monitorizada', NULL),
('Siemens Gamesa', NULL, '{}', 'Integrada en Siemens Energy. No entidad independiente.', 'no_disponible', 'motivo:integrada en Siemens Energy', NULL),
('NH Hoteles', NULL, '{}', 'No está en la BBDD. Pertenece a Minor (Tailandia).', 'no_disponible', 'motivo:no monitorizada', NULL),
('Barceló', NULL, '{}', 'No está en la BBDD. Cadena hotelera privada.', 'no_disponible', 'motivo:no monitorizada', NULL),
('Iberostar', NULL, '{}', 'No está en la BBDD. Cadena hotelera privada.', 'no_disponible', 'motivo:no monitorizada', NULL),
('RIU', NULL, '{}', 'No está en la BBDD. Cadena hotelera privada.', 'no_disponible', 'motivo:no monitorizada', NULL),

-- Diccionario corporativo: reputacion_algoritmica
('crisis reputacional', 'crisis', '{"crisis corporativa"}', 'Situación imprevista que amenaza la reputación u operaciones de una empresa.', 'reputacion_algoritmica', 'Impacto en NVM y CEM.', '{"NVM","CEM","RMM"}'),
('escándalo corporativo', 'corporate scandal', '{"escándalo","conducta irregular"}', 'Conducta irregular o ilegal con amplia repercusión pública.', 'reputacion_algoritmica', 'Alerta CEM.', '{"CEM","NVM","GAM"}'),
('reputación algorítmica', 'algorithmic reputation', '{"reputación IA"}', 'Percepción que los modelos de IA tienen de una empresa. Núcleo de RepIndex.', 'reputacion_algoritmica', 'Score RIX global.', '{"NVM","DRM","SIM","RMM","CEM","GAM","DCM","CXM"}'),
('brecha narrativa', 'narrative gap', '{"narrative gap"}', 'Diferencia entre relato corporativo y percepción algorítmica.', 'reputacion_algoritmica', 'Medir con DRM.', '{"DRM","NVM","DCM"}'),
('cuota de voz algorítmica', 'algorithmic share of voice', '{"SOV algorítmico"}', 'Presencia relativa en respuestas de IA vs competidores.', 'reputacion_algoritmica', 'Ranking comparativo RIX.', '{"NVM","RMM"}'),
('delta reputacional', 'reputational delta', '{"variación RIX"}', 'Variación en el índice RIX entre periodos.', 'reputacion_algoritmica', 'skillGetCompanyEvolution.', '{"NVM","DRM"}'),
('señal predictiva', 'predictive signal', '{}', 'Indicador que anticipa riesgo u oportunidad.', 'reputacion_algoritmica', 'Evolución temporal de subscores.', '{"NVM","CEM","SIM"}'),
('riesgo reputacional algorítmico', 'algorithmic reputational risk', '{}', 'Exposición a deterioro en percepción IA.', 'reputacion_algoritmica', 'Flags de calidad y DRM.', '{"DRM","CEM","NVM"}'),
('boicot concepto', 'boycott', '{"campaña de boicot"}', 'Campaña organizada de rechazo de productos.', 'reputacion_algoritmica', NULL, '{"NVM","DCM","CEM"}'),
('cancelación concepto', 'cancel culture', '{"cancel culture"}', 'Rechazo masivo en redes hacia una empresa.', 'digital', NULL, '{"NVM","DCM","CEM"}'),

-- optimizacion
('ARM concepto', 'Algorithmic Reputation Management', '{"gestión de reputación algorítmica"}', 'Gestión proactiva de la reputación en modelos de IA.', 'optimizacion', 'Posicionamiento central de RepIndex.', '{"NVM","DCM","DRM"}'),
('GEO concepto', 'Generative Engine Optimization', '{}', 'Optimización para motores generativos.', 'optimizacion', NULL, '{"NVM","DCM"}'),
('prompt optimization', 'prompt optimization', '{"optimización de prompts"}', 'Optimización de contenido para modelos de IA.', 'optimizacion', NULL, '{"NVM","DCM","DRM"}'),
('error factual algorítmico', 'algorithmic factual error', '{"error factual"}', 'Dato incorrecto reproducido por IA.', 'optimizacion', 'Flags de calidad RIX.', '{"DRM","NVM","CEM"}'),
('solicitud de corrección formal', 'formal correction request', '{}', 'Comunicación a operador de IA para rectificar.', 'optimizacion', NULL, '{"DRM","NVM"}'),

-- comunicacion
('portavoz', 'spokesperson', '{}', 'Representante oficial designado.', 'comunicacion', NULL, '{"NVM","GAM"}'),
('nota de prensa', 'press release', '{"comunicado","press release"}', 'Comunicado oficial para medios.', 'comunicacion', NULL, '{"NVM","DCM"}'),
('statement', 'statement', '{"declaración formal"}', 'Declaración formal ante hecho relevante.', 'comunicacion', NULL, '{"NVM","CEM"}'),
('spin', 'spin', '{}', 'Encuadre intencionadamente favorable.', 'comunicacion', NULL, '{"NVM","DRM"}'),
('messaging', 'messaging', '{"mensajes clave"}', 'Mensajes clave consistentes.', 'comunicacion', NULL, '{"NVM","DCM"}'),
('narrativa corporativa', 'corporate narrative', '{"relato corporativo"}', 'Relato estratégico de valores y visión.', 'comunicacion', NULL, '{"NVM","DCM","DRM"}'),
('share of voice', 'share of voice', '{"SOV","cuota de voz"}', 'Porcentaje de presencia en conversación del sector.', 'comunicacion', 'Ranking comparativo RIX.', '{"NVM","RMM"}'),
('fuente Tier 1', 'Tier 1 source', '{"medio Tier 1"}', 'Medio de máxima credibilidad.', 'comunicacion', NULL, '{"NVM","DRM","SIM"}'),

-- corporativo
('stakeholder', 'stakeholder', '{"grupos de interés","partes interesadas"}', 'Persona o grupo con interés en la empresa.', 'corporativo', NULL, '{"NVM","GAM"}'),
('due diligence concepto', 'due diligence', '{"diligencia debida"}', 'Análisis exhaustivo previo a operación corporativa.', 'corporativo', NULL, '{"NVM","CEM","GAM","SIM"}'),
('due diligence reputacional', 'reputational due diligence', '{}', 'Análisis de percepción algorítmica antes de operación.', 'corporativo', 'skillGetCompanyScores + skillGetDivergenceAnalysis.', '{"NVM","DRM","CEM","GAM"}'),
('compliance concepto', 'compliance', '{"cumplimiento normativo"}', 'Cumplimiento de leyes y políticas internas.', 'corporativo', NULL, '{"GAM","CEM","SIM"}'),
('M&A concepto', 'M&A', '{"fusiones y adquisiciones"}', 'Operaciones de fusión o compra. Alta exposición reputacional.', 'corporativo', NULL, '{"CXM","NVM","CEM","GAM"}'),
('IPO concepto', 'IPO', '{"salida a bolsa"}', 'Primera venta pública de acciones.', 'corporativo', NULL, '{"CXM","NVM"}'),
('desinversión', 'divestiture', '{"venta de activos"}', 'Venta o separación de parte del negocio.', 'corporativo', NULL, '{"CXM","NVM","GAM"}'),
('greenwashing concepto', 'greenwashing', '{"lavado verde"}', 'Exageración de compromisos medioambientales.', 'esg', 'Riesgo ESG.', '{"GAM","NVM","CEM"}'),

-- financiero
('profit warning', 'profit warning', '{"alerta de beneficios"}', 'Alerta de resultados peores de lo esperado.', 'financiero', NULL, '{"CXM","NVM","CEM"}'),
('guidance', 'guidance', '{"proyecciones financieras"}', 'Proyecciones oficiales sobre resultados futuros.', 'financiero', NULL, '{"CXM","NVM"}'),
('alfa financiero', 'alpha', '{"retorno superior"}', 'Retorno superior al mercado. Divergencia RIX vs precio como fuente.', 'financiero', NULL, '{"CXM","DRM"}'),
('equity research', 'equity research', '{"análisis financiero"}', 'Informe de análisis sobre compañía cotizada.', 'financiero', NULL, '{"CXM","NVM"}'),
('screening sectorial', 'sector screening', '{"filtrado sectorial"}', 'Filtrado de empresas según criterios. skillGetCompanyRanking.', 'financiero', NULL, '{"CXM","NVM"}'),

-- legal
('litigio', 'litigation', '{"proceso judicial","demanda"}', 'Proceso judicial contra una empresa. Riesgo reputacional.', 'legal', NULL, '{"CEM","NVM","GAM"}'),
('demanda colectiva', 'class action', '{"class action"}', 'Acción legal de grupo de afectados.', 'legal', NULL, '{"CEM","NVM"}'),
('regulador concepto', 'regulator', '{"organismo regulador"}', 'Organismo supervisor: CNMC, CNMV, BdE.', 'legal', NULL, '{"GAM","SIM","CEM"}'),
('sanción concepto', 'sanction', '{"penalización","multa"}', 'Penalización por incumplimiento.', 'legal', NULL, '{"CEM","GAM","SIM"}'),
('multa antimonopolio', 'antitrust fine', '{}', 'Sanción por prácticas contra libre competencia.', 'legal', NULL, '{"CEM","GAM","SIM"}'),
('investigación regulatoria', 'regulatory investigation', '{}', 'Proceso formal de supervisión.', 'legal', NULL, '{"CEM","GAM"}'),
('inteligencia regulatoria', 'regulatory intelligence', '{}', 'Detectar tendencias normativas via IA.', 'legal', NULL, '{"GAM","SIM","NVM"}'),
('lobby concepto', 'lobbying', '{"lobbying","cabildeo"}', 'Influencia sobre reguladores.', 'institucional', NULL, '{"GAM","NVM"}'),
('relaciones institucionales', 'public affairs', '{"public affairs"}', 'Gestión de relación con gobiernos y reguladores.', 'institucional', NULL, '{"GAM","NVM"}'),

-- institucional/laboral
('ERE concepto', 'ERE', '{"expediente de regulación de empleo","despido colectivo"}', 'Reducción colectiva de plantilla.', 'institucional', NULL, '{"NVM","CEM","GAM"}'),
('huelga', 'strike', '{"conflicto laboral"}', 'Cese de actividad por trabajadores.', 'institucional', NULL, '{"NVM","CEM"}'),
('cultura corporativa', 'corporate culture', '{}', 'Valores y comportamientos compartidos.', 'institucional', NULL, '{"NVM","GAM"}'),
('employer branding', 'employer branding', '{"marca empleadora"}', 'Reputación como empleador.', 'institucional', NULL, '{"NVM","GAM"}'),
('marca empleadora algorítmica', 'algorithmic employer brand', '{}', 'Percepción IA de empresa como lugar de trabajo.', 'institucional', NULL, '{"NVM","GAM"}'),

-- esg
('ESG criterios', 'ESG criteria', '{"criterios ESG"}', 'Criterios Ambientales, Sociales y de Gobernanza.', 'esg', NULL, '{"GAM","NVM","CEM"}'),
('accountability', 'accountability', '{"rendición de cuentas"}', 'Responsabilidad pública ante stakeholders.', 'esg', NULL, '{"GAM","NVM"}'),
('transparencia corporativa', 'corporate transparency', '{"transparencia"}', 'Comunicación abierta y verificable.', 'esg', NULL, '{"GAM","NVM","DCM"}'),
('buen gobierno', 'good governance', '{"gobierno corporativo"}', 'Dirección con integridad y equidad.', 'esg', NULL, '{"GAM","NVM"}'),
('diversidad e inclusión', 'diversity and inclusion', '{"D&I","diversidad"}', 'Representación equitativa.', 'esg', NULL, '{"GAM","NVM"}'),
('RSC concepto', 'CSR', '{"responsabilidad social corporativa"}', 'Compromiso voluntario con bienestar social y ambiental.', 'esg', NULL, '{"GAM","NVM"}'),
('neutralidad de carbono', 'net zero', '{"net zero"}', 'Compensar totalidad de emisiones CO2.', 'esg', NULL, '{"GAM","NVM"}'),
('huella de carbono', 'carbon footprint', '{"emisiones CO2"}', 'Total emisiones gases efecto invernadero.', 'esg', NULL, '{"GAM","NVM"}'),

-- digital
('Glassdoor', 'Glassdoor', '{}', 'Plataforma de valoraciones de empleados. Impacta employer branding algorítmico.', 'digital', NULL, '{"NVM","GAM"}'),
('fake news', 'fake news', '{"desinformación","noticias falsas"}', 'Información falsa intencionada.', 'digital', NULL, '{"NVM","CEM","DRM"}'),
('trending topic', 'trending topic', '{"TT"}', 'Tema con alto volumen de menciones.', 'digital', NULL, '{"NVM","DCM"}'),
('viral concepto', 'viral', '{"contenido viral"}', 'Contenido de difusión masiva.', 'digital', NULL, '{"NVM","DCM"}'),
('reputación online', 'online reputation', '{"reputación digital"}', 'Percepción en entorno digital.', 'digital', NULL, '{"NVM","DCM","DRM"}'),
('fact-checking', 'fact-checking', '{"verificación de hechos"}', 'Verificación de veracidad de declaraciones.', 'digital', NULL, '{"NVM","DRM","SIM"}'),

-- pericial
('daño reputacional', 'reputational damage', '{"perjuicio reputacional"}', 'Deterioro measurable en percepción pública.', 'pericial', 'Cuantificable con delta RIX.', '{"NVM","DRM","CEM"}'),
('nexo causal', 'causal nexus', '{}', 'Relación directa entre hecho y daño.', 'pericial', NULL, '{"NVM","DRM"}'),
('cuantificación del daño', 'damage quantification', '{}', 'Asignar valor económico al perjuicio.', 'pericial', 'skillGetCompanyEvolution + skillGetDivergenceAnalysis.', '{"NVM","DRM","CXM"}'),
('línea base reputacional', 'reputational baseline', '{"baseline"}', 'Estado reputacional pre-evento.', 'pericial', 'RIX score pre-evento.', '{"NVM","DRM"}'),
('hecho desencadenante', 'trigger event', '{"evento detonante"}', 'Acontecimiento que origina deterioro.', 'pericial', NULL, '{"NVM","CEM"}'),
('imputabilidad', 'imputability', '{}', 'Atribución del daño a sujeto concreto.', 'pericial', NULL, '{"NVM","CEM"}'),
('difamación corporativa', 'corporate defamation', '{}', 'Declaraciones falsas públicas con perjuicio.', 'pericial', NULL, '{"NVM","CEM","DRM"}'),
('informe pericial', 'expert report', '{"dictamen pericial"}', 'Documento que acredita daño reputacional en proceso legal.', 'pericial', NULL, '{"NVM","DRM","CEM"}'),
('análisis forense reputacional', 'reputational forensic analysis', '{}', 'Examen técnico de percepción algorítmica histórica.', 'pericial', 'skillGetCompanyEvolution.', '{"NVM","DRM","CEM"}'),
('medición longitudinal', 'longitudinal measurement', '{}', 'Análisis temporal para identificar rupturas.', 'pericial', 'skillGetCompanyEvolution.', '{"NVM","DRM"}'),
('comparativa sectorial concepto', 'sector comparison', '{"benchmarking sectorial"}', 'Contraste RIX vs competidores.', 'pericial', 'skillGetSectorComparison.', '{"NVM","RMM"}'),
('recuperación reputacional', 'reputational recovery', '{}', 'Evolución RIX post-evento dañino.', 'pericial', NULL, '{"NVM","DRM"}'),

-- roles
('presidente cargo', 'chairman', '{"chairman","presidente del consejo"}', 'Máximo responsable del Consejo de Administración.', 'roles', NULL, '{"NVM","GAM"}'),
('consejero delegado', 'CEO', '{"CEO","chief executive officer"}', 'Principal ejecutivo de la empresa.', 'roles', NULL, '{"NVM","GAM"}'),
('CFO cargo', 'CFO', '{"chief financial officer","director financiero"}', 'Responsable de gestión financiera.', 'roles', NULL, '{"CXM","GAM"}'),
('COO cargo', 'COO', '{"chief operating officer","director de operaciones"}', 'Responsable de eficiencia operativa.', 'roles', NULL, '{"NVM","GAM"}'),
('CMO cargo', 'CMO', '{"chief marketing officer","director de marketing"}', 'Responsable de estrategia de marca.', 'roles', NULL, '{"NVM","DCM"}'),
('CCO cargo', 'CCO', '{"chief communications officer","director de comunicación","dircom"}', 'Responsable de reputación corporativa.', 'roles', NULL, '{"NVM","DCM","GAM"}'),
('CTO cargo', 'CTO', '{"chief technology officer","director de tecnología"}', 'Responsable de estrategia tecnológica.', 'roles', NULL, '{"DCM","NVM"}'),
('CISO cargo', 'CISO', '{"chief information security officer"}', 'Responsable de ciberseguridad.', 'roles', NULL, '{"CEM","GAM","DCM"}'),
('CLO cargo', 'CLO', '{"chief legal officer","director jurídico"}', 'Responsable legal.', 'roles', NULL, '{"CEM","GAM","SIM"}'),
('CHRO cargo', 'CHRO', '{"chief human resources officer","director de RRHH"}', 'Responsable de gestión del talento.', 'roles', NULL, '{"NVM","GAM"}'),
('CSO cargo', 'CSO', '{"chief sustainability officer","director de sostenibilidad"}', 'Responsable de estrategia ESG.', 'roles', NULL, '{"GAM","NVM"}'),
('CDO cargo', 'CDO', '{"chief digital officer","director digital"}', 'Responsable de transformación digital.', 'roles', NULL, '{"DCM","NVM"}'),
('director general', 'general manager', '{"DG"}', 'Equivalente operativo al CEO en empresas españolas.', 'roles', NULL, '{"NVM","GAM"}'),
('director de relaciones con inversores', 'investor relations director', '{"IR","relaciones con inversores"}', 'Gestiona comunicación financiera.', 'roles', NULL, '{"CXM","NVM"}'),
('director de asuntos públicos', 'public affairs director', '{"asuntos públicos"}', 'Gestiona relación con administraciones.', 'roles', NULL, '{"GAM","NVM"}'),
('fundador', 'founder', '{"co-fundador","cofundador"}', 'Creador original. Reputación vinculada a la organización.', 'roles', NULL, '{"NVM","GAM"}'),
('accionista de referencia', 'reference shareholder', '{"accionista mayoritario"}', 'Inversor con participación significativa.', 'roles', NULL, '{"GAM","CXM"}');
